/*
###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID pc231.ee.hacettepe.edu.tr)
#  Generated on:      Thu Dec 25 09:54:04 2025
#  Design:            rv32im_integrated_macro
#  Command:           saveNetlist outputs/rv32im_integrated/rv32im_integrated_macro_netlist.v -excludeLeafCell
###############################################################
*/
module rv32im_integrated_macro (
	clk, 
	rst_n, 
	iwb_adr_o, 
	iwb_dat_i, 
	iwb_cyc_o, 
	iwb_stb_o, 
	iwb_ack_i, 
	dwb_adr_o, 
	dwb_dat_o, 
	dwb_dat_i, 
	dwb_we_o, 
	dwb_sel_o, 
	dwb_cyc_o, 
	dwb_stb_o, 
	dwb_ack_i, 
	dwb_err_i, 
	interrupts);
   input clk;
   input rst_n;
   output [31:0] iwb_adr_o;
   input [31:0] iwb_dat_i;
   output iwb_cyc_o;
   output iwb_stb_o;
   input iwb_ack_i;
   output [31:0] dwb_adr_o;
   output [31:0] dwb_dat_o;
   input [31:0] dwb_dat_i;
   output dwb_we_o;
   output [3:0] dwb_sel_o;
   output dwb_cyc_o;
   output dwb_stb_o;
   input dwb_ack_i;
   input dwb_err_i;
   input [31:0] interrupts;

   // Internal wires
   wire [63:0] mdu_product;
   wire [31:0] mdu_quotient;
   wire [31:0] mdu_remainder;
   wire [2:0] mdu_funct3;
   wire [31:0] mdu_operand_a;
   wire [31:0] mdu_operand_b;
   wire mdu_ack;
   wire mdu_busy;
   wire mdu_done;
   wire mdu_start;

   core_macro u_core_macro (.clk(clk),
	.rst_n(rst_n),
	.iwb_adr_o(iwb_adr_o),
	.iwb_dat_i(iwb_dat_i),
	.iwb_cyc_o(iwb_cyc_o),
	.iwb_stb_o(iwb_stb_o),
	.iwb_ack_i(iwb_ack_i),
	.dwb_adr_o(dwb_adr_o),
	.dwb_dat_o(dwb_dat_o),
	.dwb_dat_i(dwb_dat_i),
	.dwb_we_o(dwb_we_o),
	.dwb_sel_o(dwb_sel_o),
	.dwb_cyc_o(dwb_cyc_o),
	.dwb_stb_o(dwb_stb_o),
	.dwb_ack_i(dwb_ack_i),
	.dwb_err_i(dwb_err_i),
	.mdu_start(mdu_start),
	.mdu_ack(mdu_ack),
	.mdu_funct3(mdu_funct3),
	.mdu_operand_a(mdu_operand_a),
	.mdu_operand_b(mdu_operand_b),
	.mdu_busy(mdu_busy),
	.mdu_done(mdu_done),
	.mdu_product(mdu_product),
	.mdu_quotient(mdu_quotient),
	.mdu_remainder(mdu_remainder),
	.interrupts(interrupts));
   mdu_macro u_mdu_macro (.start(mdu_start),
	.rst_n(rst_n),
	.remainder(mdu_remainder),
	.quotient(mdu_quotient),
	.product(mdu_product),
	.operand_b(mdu_operand_b),
	.operand_a(mdu_operand_a),
	.funct3(mdu_funct3),
	.done(mdu_done),
	.clk(clk),
	.busy(mdu_busy),
	.ack(mdu_ack));
endmodule

