/*
###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID pc231.ee.hacettepe.edu.tr)
#  Generated on:      Wed Dec 24 12:11:45 2025
#  Design:            memory_macro
#  Command:           saveNetlist outputs/memory_macro/memory_macro_netlist.v -excludeLeafCell
###############################################################
*/
module memory_macro (
	clk, 
	rst_n, 
	iwb_adr_i, 
	iwb_dat_o, 
	iwb_dat_i, 
	iwb_we_i, 
	iwb_sel_i, 
	iwb_cyc_i, 
	iwb_stb_i, 
	iwb_ack_o, 
	iwb_err_o, 
	dwb_adr_i, 
	dwb_dat_o, 
	dwb_dat_i, 
	dwb_we_i, 
	dwb_sel_i, 
	dwb_cyc_i, 
	dwb_stb_i, 
	dwb_ack_o, 
	dwb_err_o, 
	ext_mem_adr_o, 
	ext_mem_dat_o, 
	ext_mem_dat_i, 
	ext_mem_we_o, 
	ext_mem_sel_o, 
	ext_mem_cyc_o, 
	ext_mem_stb_o, 
	ext_mem_ack_i, 
	ext_mem_err_i, 
	rom_ready, 
	ram_ready, 
	memory_status);
   input clk;
   input rst_n;
   input [31:0] iwb_adr_i;
   output [31:0] iwb_dat_o;
   input [31:0] iwb_dat_i;
   input iwb_we_i;
   input [3:0] iwb_sel_i;
   input iwb_cyc_i;
   input iwb_stb_i;
   output iwb_ack_o;
   output iwb_err_o;
   input [31:0] dwb_adr_i;
   output [31:0] dwb_dat_o;
   input [31:0] dwb_dat_i;
   input dwb_we_i;
   input [3:0] dwb_sel_i;
   input dwb_cyc_i;
   input dwb_stb_i;
   output dwb_ack_o;
   output dwb_err_o;
   output [31:0] ext_mem_adr_o;
   output [31:0] ext_mem_dat_o;
   input [31:0] ext_mem_dat_i;
   output ext_mem_we_o;
   output [3:0] ext_mem_sel_o;
   output ext_mem_cyc_o;
   output ext_mem_stb_o;
   input ext_mem_ack_i;
   input ext_mem_err_i;
   output rom_ready;
   output ram_ready;
   output [31:0] memory_status;

   // Internal wires
   wire n_141;
   wire n_140;
   wire n_139;
   wire n_138;
   wire n_137;
   wire n_136;
   wire n_135;
   wire n_134;
   wire n_133;
   wire n_132;
   wire n_131;
   wire n_130;
   wire n_129;
   wire n_128;
   wire n_127;
   wire n_126;
   wire n_125;
   wire n_124;
   wire n_123;
   wire n_122;
   wire n_121;
   wire n_120;
   wire n_119;
   wire n_118;
   wire n_117;
   wire n_116;
   wire n_115;
   wire n_114;
   wire n_113;
   wire n_112;
   wire n_111;
   wire n_103;
   wire n_18;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire ext_ack;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_173;
   wire n_174;
   wire n_181;
   wire n_182;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_223;
   wire n_253;
   wire n_259;
   wire n_447;
   wire n_448;
   wire ram_ack;
   wire rom_ack;

   assign memory_status[12] = ext_mem_ack_i ;
   assign ext_mem_stb_o = ext_mem_cyc_o ;
   assign dwb_err_o = iwb_err_o ;

   sky130_osu_sc_18T_ms__tielo LTIELO_24 (.Y(memory_status[0]));
   sky130_osu_sc_18T_ms__tielo LTIELO_23 (.Y(memory_status[3]));
   sky130_osu_sc_18T_ms__tielo LTIELO_22 (.Y(memory_status[5]));
   sky130_osu_sc_18T_ms__tielo LTIELO_21 (.Y(memory_status[6]));
   sky130_osu_sc_18T_ms__tielo LTIELO_20 (.Y(memory_status[8]));
   sky130_osu_sc_18T_ms__tielo LTIELO_19 (.Y(memory_status[9]));
   sky130_osu_sc_18T_ms__tielo LTIELO_18 (.Y(memory_status[10]));
   sky130_osu_sc_18T_ms__tielo LTIELO_17 (.Y(memory_status[11]));
   sky130_osu_sc_18T_ms__tielo LTIELO_16 (.Y(memory_status[13]));
   sky130_osu_sc_18T_ms__tielo LTIELO_15 (.Y(memory_status[16]));
   sky130_osu_sc_18T_ms__tielo LTIELO_14 (.Y(memory_status[17]));
   sky130_osu_sc_18T_ms__tielo LTIELO_13 (.Y(memory_status[18]));
   sky130_osu_sc_18T_ms__tielo LTIELO_12 (.Y(memory_status[19]));
   sky130_osu_sc_18T_ms__tielo LTIELO_11 (.Y(memory_status[20]));
   sky130_osu_sc_18T_ms__tielo LTIELO_10 (.Y(memory_status[21]));
   sky130_osu_sc_18T_ms__tielo LTIELO_9 (.Y(memory_status[22]));
   sky130_osu_sc_18T_ms__tielo LTIELO_8 (.Y(memory_status[23]));
   sky130_osu_sc_18T_ms__tielo LTIELO_7 (.Y(memory_status[24]));
   sky130_osu_sc_18T_ms__tielo LTIELO_6 (.Y(memory_status[25]));
   sky130_osu_sc_18T_ms__tielo LTIELO_5 (.Y(memory_status[26]));
   sky130_osu_sc_18T_ms__tielo LTIELO_4 (.Y(memory_status[27]));
   sky130_osu_sc_18T_ms__tielo LTIELO_3 (.Y(memory_status[28]));
   sky130_osu_sc_18T_ms__tielo LTIELO_2 (.Y(memory_status[29]));
   sky130_osu_sc_18T_ms__tielo LTIELO_1 (.Y(memory_status[30]));
   sky130_osu_sc_18T_ms__tielo LTIELO (.Y(memory_status[31]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_7 (.Y(memory_status[1]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_6 (.Y(memory_status[2]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_5 (.Y(memory_status[4]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_4 (.Y(memory_status[7]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_3 (.Y(memory_status[14]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_2 (.Y(memory_status[15]));
   sky130_osu_sc_18T_ms__tiehi LTIEHI_1 (.Y(ram_ready));
   sky130_osu_sc_18T_ms__tiehi LTIEHI (.Y(rom_ready));
   sky130_osu_sc_18T_ms__oai22_l g7453__2398 (.Y(dwb_ack_o),
	.A0(ram_ack),
	.A1(n_192),
	.B0(n_195),
	.B1(ext_ack));
   sky130_osu_sc_18T_ms__oai22_l g7454__5107 (.Y(iwb_ack_o),
	.A0(rom_ack),
	.A1(n_188),
	.B0(n_194),
	.B1(ext_ack));
   sky130_osu_sc_18T_ms__nand2_l g7518__6260 (.Y(iwb_dat_o[0]),
	.A(n_186),
	.B(n_253));
   sky130_osu_sc_18T_ms__and2_l g7485__4319 (.Y(dwb_dat_o[0]),
	.A(n_259),
	.B(ext_mem_dat_i[0]));
   sky130_osu_sc_18T_ms__and2_l g7486__8428 (.Y(dwb_dat_o[31]),
	.A(n_259),
	.B(ext_mem_dat_i[31]));
   sky130_osu_sc_18T_ms__and2_l g7456__5526 (.Y(dwb_dat_o[30]),
	.A(n_259),
	.B(ext_mem_dat_i[30]));
   sky130_osu_sc_18T_ms__and2_l g7484__6783 (.Y(dwb_dat_o[4]),
	.A(n_259),
	.B(ext_mem_dat_i[4]));
   sky130_osu_sc_18T_ms__and2_l g7471__3680 (.Y(dwb_dat_o[29]),
	.A(n_259),
	.B(ext_mem_dat_i[29]));
   sky130_osu_sc_18T_ms__and2_l g7472__1617 (.Y(dwb_dat_o[28]),
	.A(n_259),
	.B(ext_mem_dat_i[28]));
   sky130_osu_sc_18T_ms__nand2_l g7516__2802 (.Y(iwb_dat_o[4]),
	.A(n_189),
	.B(n_253));
   sky130_osu_sc_18T_ms__nand2_l g7517__1705 (.Y(iwb_dat_o[1]),
	.A(n_187),
	.B(n_253));
   sky130_osu_sc_18T_ms__and2_l g7459__5122 (.Y(dwb_dat_o[25]),
	.A(n_259),
	.B(ext_mem_dat_i[25]));
   sky130_osu_sc_18T_ms__and2_l g7460__8246 (.Y(dwb_dat_o[24]),
	.A(n_259),
	.B(ext_mem_dat_i[24]));
   sky130_osu_sc_18T_ms__and2_l g7461__7098 (.Y(dwb_dat_o[23]),
	.A(n_259),
	.B(ext_mem_dat_i[23]));
   sky130_osu_sc_18T_ms__and2_l g7480__6131 (.Y(dwb_dat_o[12]),
	.A(n_259),
	.B(ext_mem_dat_i[12]));
   sky130_osu_sc_18T_ms__and2_l g7462__1881 (.Y(dwb_dat_o[22]),
	.A(n_259),
	.B(ext_mem_dat_i[22]));
   sky130_osu_sc_18T_ms__and2_l g7463__5115 (.Y(dwb_dat_o[21]),
	.A(n_259),
	.B(ext_mem_dat_i[21]));
   sky130_osu_sc_18T_ms__and2_l g7464__7482 (.Y(dwb_dat_o[20]),
	.A(n_259),
	.B(ext_mem_dat_i[20]));
   sky130_osu_sc_18T_ms__and2_l g7465__4733 (.Y(dwb_dat_o[19]),
	.A(n_259),
	.B(ext_mem_dat_i[19]));
   sky130_osu_sc_18T_ms__and2_l g7476__6161 (.Y(dwb_dat_o[8]),
	.A(n_259),
	.B(ext_mem_dat_i[8]));
   sky130_osu_sc_18T_ms__and2_l g7467__9315 (.Y(dwb_dat_o[17]),
	.A(n_259),
	.B(ext_mem_dat_i[17]));
   sky130_osu_sc_18T_ms__and2_l g7468__9945 (.Y(dwb_dat_o[16]),
	.A(n_259),
	.B(ext_mem_dat_i[16]));
   sky130_osu_sc_18T_ms__and2_l g7469__2883 (.Y(dwb_dat_o[15]),
	.A(n_259),
	.B(ext_mem_dat_i[15]));
   sky130_osu_sc_18T_ms__and2_l g7470__2346 (.Y(dwb_dat_o[14]),
	.A(n_259),
	.B(ext_mem_dat_i[14]));
   sky130_osu_sc_18T_ms__and2_l g7455__1666 (.Y(dwb_dat_o[13]),
	.A(n_259),
	.B(ext_mem_dat_i[13]));
   sky130_osu_sc_18T_ms__and2_l g7457__7410 (.Y(dwb_dat_o[27]),
	.A(n_259),
	.B(ext_mem_dat_i[27]));
   sky130_osu_sc_18T_ms__and2_l g7474__6417 (.Y(dwb_dat_o[10]),
	.A(n_259),
	.B(ext_mem_dat_i[10]));
   sky130_osu_sc_18T_ms__and2_l g7475__5477 (.Y(dwb_dat_o[9]),
	.A(n_259),
	.B(ext_mem_dat_i[9]));
   sky130_osu_sc_18T_ms__and2_l g7466__2398 (.Y(dwb_dat_o[18]),
	.A(n_259),
	.B(ext_mem_dat_i[18]));
   sky130_osu_sc_18T_ms__and2_l g7477__5107 (.Y(dwb_dat_o[7]),
	.A(n_259),
	.B(ext_mem_dat_i[7]));
   sky130_osu_sc_18T_ms__and2_l g7478__6260 (.Y(dwb_dat_o[6]),
	.A(n_259),
	.B(ext_mem_dat_i[6]));
   sky130_osu_sc_18T_ms__and2_l g7479__4319 (.Y(dwb_dat_o[5]),
	.A(n_259),
	.B(ext_mem_dat_i[5]));
   sky130_osu_sc_18T_ms__and2_l g7458__8428 (.Y(dwb_dat_o[26]),
	.A(n_259),
	.B(ext_mem_dat_i[26]));
   sky130_osu_sc_18T_ms__and2_l g7482__5526 (.Y(dwb_dat_o[2]),
	.A(n_259),
	.B(ext_mem_dat_i[2]));
   sky130_osu_sc_18T_ms__and2_l g7483__6783 (.Y(dwb_dat_o[1]),
	.A(n_259),
	.B(ext_mem_dat_i[1]));
   sky130_osu_sc_18T_ms__and2_l g7473__3680 (.Y(dwb_dat_o[11]),
	.A(n_259),
	.B(ext_mem_dat_i[11]));
   sky130_osu_sc_18T_ms__and2_l g7481__1617 (.Y(dwb_dat_o[3]),
	.A(n_259),
	.B(ext_mem_dat_i[3]));
   sky130_osu_sc_18T_ms__and2_l g7511__2802 (.Y(iwb_dat_o[25]),
	.A(n_223),
	.B(ext_mem_dat_i[25]));
   sky130_osu_sc_18T_ms__and2_l g7510__1705 (.Y(iwb_dat_o[31]),
	.A(n_223),
	.B(ext_mem_dat_i[31]));
   sky130_osu_sc_18T_ms__and2_l g7490__5122 (.Y(iwb_dat_o[30]),
	.A(n_223),
	.B(ext_mem_dat_i[30]));
   sky130_osu_sc_18T_ms__and2_l g7513__8246 (.Y(iwb_dat_o[29]),
	.A(n_223),
	.B(ext_mem_dat_i[29]));
   sky130_osu_sc_18T_ms__and2_l g7504__7098 (.Y(iwb_dat_o[28]),
	.A(n_223),
	.B(ext_mem_dat_i[28]));
   sky130_osu_sc_18T_ms__and2_l g7506__6131 (.Y(iwb_dat_o[27]),
	.A(n_223),
	.B(ext_mem_dat_i[27]));
   sky130_osu_sc_18T_ms__and2_l g7508__1881 (.Y(iwb_dat_o[26]),
	.A(n_223),
	.B(ext_mem_dat_i[26]));
   sky130_osu_sc_18T_ms__and2_l g7507__5115 (.Y(iwb_dat_o[3]),
	.A(n_223),
	.B(ext_mem_dat_i[3]));
   sky130_osu_sc_18T_ms__and2_l g7500__7482 (.Y(iwb_dat_o[8]),
	.A(n_223),
	.B(ext_mem_dat_i[8]));
   sky130_osu_sc_18T_ms__and2_l g7512__4733 (.Y(iwb_dat_o[24]),
	.A(n_223),
	.B(ext_mem_dat_i[24]));
   sky130_osu_sc_18T_ms__and2_l g7514__6161 (.Y(iwb_dat_o[23]),
	.A(n_223),
	.B(ext_mem_dat_i[23]));
   sky130_osu_sc_18T_ms__and2_l g7515__9315 (.Y(iwb_dat_o[22]),
	.A(n_223),
	.B(ext_mem_dat_i[22]));
   sky130_osu_sc_18T_ms__and2_l g7497__9945 (.Y(iwb_dat_o[12]),
	.A(n_223),
	.B(ext_mem_dat_i[12]));
   sky130_osu_sc_18T_ms__and2_l g7492__2883 (.Y(iwb_dat_o[21]),
	.A(n_223),
	.B(ext_mem_dat_i[21]));
   sky130_osu_sc_18T_ms__and2_l g7503__2346 (.Y(iwb_dat_o[20]),
	.A(n_223),
	.B(ext_mem_dat_i[20]));
   sky130_osu_sc_18T_ms__and2_l g7498__1666 (.Y(iwb_dat_o[11]),
	.A(n_223),
	.B(ext_mem_dat_i[11]));
   sky130_osu_sc_18T_ms__and2_l g7489__7410 (.Y(iwb_dat_o[18]),
	.A(n_223),
	.B(ext_mem_dat_i[18]));
   sky130_osu_sc_18T_ms__and2_l g7493__6417 (.Y(iwb_dat_o[17]),
	.A(n_223),
	.B(ext_mem_dat_i[17]));
   sky130_osu_sc_18T_ms__and2_l g7491__5477 (.Y(iwb_dat_o[16]),
	.A(n_223),
	.B(ext_mem_dat_i[16]));
   sky130_osu_sc_18T_ms__and2_l g7494__2398 (.Y(iwb_dat_o[15]),
	.A(n_223),
	.B(ext_mem_dat_i[15]));
   sky130_osu_sc_18T_ms__and2_l g7495__5107 (.Y(iwb_dat_o[14]),
	.A(n_223),
	.B(ext_mem_dat_i[14]));
   sky130_osu_sc_18T_ms__and2_l g7496__6260 (.Y(iwb_dat_o[13]),
	.A(n_223),
	.B(ext_mem_dat_i[13]));
   sky130_osu_sc_18T_ms__and2_l g7488__4319 (.Y(iwb_dat_o[19]),
	.A(n_223),
	.B(ext_mem_dat_i[19]));
   sky130_osu_sc_18T_ms__and2_l g7499__8428 (.Y(iwb_dat_o[10]),
	.A(n_223),
	.B(ext_mem_dat_i[10]));
   sky130_osu_sc_18T_ms__and2_l g7501__5526 (.Y(iwb_dat_o[9]),
	.A(n_223),
	.B(ext_mem_dat_i[9]));
   sky130_osu_sc_18T_ms__and2_l g7502__6783 (.Y(iwb_dat_o[7]),
	.A(n_223),
	.B(ext_mem_dat_i[7]));
   sky130_osu_sc_18T_ms__and2_l g7487__3680 (.Y(iwb_dat_o[6]),
	.A(n_223),
	.B(ext_mem_dat_i[6]));
   sky130_osu_sc_18T_ms__and2_l g7505__1617 (.Y(iwb_dat_o[5]),
	.A(n_223),
	.B(ext_mem_dat_i[5]));
   sky130_osu_sc_18T_ms__and2_l g7509__2802 (.Y(iwb_dat_o[2]),
	.A(n_223),
	.B(ext_mem_dat_i[2]));
   sky130_osu_sc_18T_ms__inv_1 g7522 (.Y(n_195),
	.A(n_259));
   sky130_osu_sc_18T_ms__inv_1 g7519 (.Y(n_194),
	.A(n_223));
   sky130_osu_sc_18T_ms__oai21_l g7523__1705 (.Y(n_253),
	.A0(n_173),
	.A1(n_182),
	.B0(n_193));
   sky130_osu_sc_18T_ms__dffr_1 rom_ack_reg (.Q(UNCONNECTED),
	.QN(rom_ack),
	.CK(clk),
	.D(n_185),
	.RN(rst_n));
   sky130_osu_sc_18T_ms__dffr_1 ram_ack_reg (.Q(UNCONNECTED0),
	.QN(ram_ack),
	.CK(clk),
	.D(n_191),
	.RN(rst_n));
   sky130_osu_sc_18T_ms__oai21_l g7524__5122 (.Y(n_259),
	.A0(n_190),
	.A1(n_184),
	.B0(n_193));
   sky130_osu_sc_18T_ms__inv_1 g7525 (.Y(n_192),
	.A(n_191));
   sky130_osu_sc_18T_ms__oai21_l g7521__8246 (.Y(n_223),
	.A0(n_193),
	.A1(n_174),
	.B0(n_190));
   sky130_osu_sc_18T_ms__nand2_l g7528__7098 (.Y(n_189),
	.A(n_188),
	.B(ext_mem_dat_i[4]));
   sky130_osu_sc_18T_ms__nand2_l g7529__6131 (.Y(n_187),
	.A(n_188),
	.B(ext_mem_dat_i[1]));
   sky130_osu_sc_18T_ms__nand2_l g7530__1881 (.Y(n_186),
	.A(n_188),
	.B(ext_mem_dat_i[0]));
   sky130_osu_sc_18T_ms__nor2_1 g7527__5115 (.Y(n_191),
	.A(dwb_adr_i[31]),
	.B(n_448));
   sky130_osu_sc_18T_ms__inv_1 g7564 (.Y(n_185),
	.A(n_188));
   sky130_osu_sc_18T_ms__nand2_1 g7600__7482 (.Y(n_188),
	.A(n_19),
	.B(n_181));
   sky130_osu_sc_18T_ms__inv_1 g7563 (.Y(n_184),
	.A(n_448));
   sky130_osu_sc_18T_ms__nor2_l g7583__4733 (.Y(n_182),
	.A(iwb_adr_i[31]),
	.B(n_181));
   sky130_osu_sc_18T_ms__inv_l g7636 (.Y(ext_mem_adr_o[13]),
	.A(n_77));
   sky130_osu_sc_18T_ms__inv_l g7617 (.Y(ext_mem_adr_o[21]),
	.A(n_56));
   sky130_osu_sc_18T_ms__inv_l g7618 (.Y(ext_mem_dat_o[5]),
	.A(n_75));
   sky130_osu_sc_18T_ms__inv_l g7533 (.Y(ext_mem_adr_o[29]),
	.A(n_41));
   sky130_osu_sc_18T_ms__inv_l g7619 (.Y(ext_mem_dat_o[14]),
	.A(n_109));
   sky130_osu_sc_18T_ms__inv_l g7549 (.Y(ext_mem_dat_o[28]),
	.A(n_110));
   sky130_osu_sc_18T_ms__nor2_l g7568__6161 (.Y(n_174),
	.A(n_173),
	.B(n_39));
   sky130_osu_sc_18T_ms__inv_l g7620 (.Y(ext_mem_adr_o[20]),
	.A(n_104));
   sky130_osu_sc_18T_ms__inv_l g7621 (.Y(ext_mem_adr_o[19]),
	.A(n_106));
   sky130_osu_sc_18T_ms__inv_l g7550 (.Y(ext_mem_dat_o[27]),
	.A(n_105));
   sky130_osu_sc_18T_ms__inv_l g7622 (.Y(ext_mem_dat_o[3]),
	.A(n_102));
   sky130_osu_sc_18T_ms__inv_l g7623 (.Y(ext_mem_dat_o[2]),
	.A(n_101));
   sky130_osu_sc_18T_ms__inv_l g7551 (.Y(ext_mem_dat_o[26]),
	.A(n_100));
   sky130_osu_sc_18T_ms__inv_l g7624 (.Y(ext_mem_adr_o[18]),
	.A(n_98));
   sky130_osu_sc_18T_ms__inv_l g7534 (.Y(ext_mem_adr_o[12]),
	.A(n_99));
   sky130_osu_sc_18T_ms__inv_l g7625 (.Y(ext_mem_dat_o[1]),
	.A(n_96));
   sky130_osu_sc_18T_ms__inv_l g7552 (.Y(ext_mem_dat_o[25]),
	.A(n_97));
   sky130_osu_sc_18T_ms__inv_l g7626 (.Y(ext_mem_adr_o[17]),
	.A(n_94));
   sky130_osu_sc_18T_ms__inv_l g7627 (.Y(ext_mem_dat_o[0]),
	.A(n_92));
   sky130_osu_sc_18T_ms__inv_l g7553 (.Y(ext_mem_dat_o[24]),
	.A(n_93));
   sky130_osu_sc_18T_ms__inv_l g7628 (.Y(ext_mem_adr_o[16]),
	.A(n_91));
   sky130_osu_sc_18T_ms__inv_l g7535 (.Y(ext_mem_adr_o[11]),
	.A(n_95));
   sky130_osu_sc_18T_ms__inv_l g7629 (.Y(ext_mem_we_o),
	.A(n_89));
   sky130_osu_sc_18T_ms__inv_l g7554 (.Y(ext_mem_dat_o[23]),
	.A(n_90));
   sky130_osu_sc_18T_ms__inv_l g7630 (.Y(ext_mem_adr_o[15]),
	.A(n_87));
   sky130_osu_sc_18T_ms__inv_l g7631 (.Y(ext_mem_sel_o[3]),
	.A(n_85));
   sky130_osu_sc_18T_ms__inv_l g7555 (.Y(ext_mem_dat_o[22]),
	.A(n_86));
   sky130_osu_sc_18T_ms__inv_l g7632 (.Y(ext_mem_sel_o[2]),
	.A(n_84));
   sky130_osu_sc_18T_ms__inv_l g7536 (.Y(ext_mem_adr_o[10]),
	.A(n_88));
   sky130_osu_sc_18T_ms__inv_l g7633 (.Y(ext_mem_adr_o[14]),
	.A(n_82));
   sky130_osu_sc_18T_ms__inv_l g7556 (.Y(ext_mem_dat_o[21]),
	.A(n_83));
   sky130_osu_sc_18T_ms__inv_l g7634 (.Y(ext_mem_sel_o[1]),
	.A(n_80));
   sky130_osu_sc_18T_ms__inv_l g7635 (.Y(ext_mem_sel_o[0]),
	.A(n_78));
   sky130_osu_sc_18T_ms__inv_l g7557 (.Y(ext_mem_dat_o[20]),
	.A(n_79));
   sky130_osu_sc_18T_ms__inv_l g7548 (.Y(ext_mem_dat_o[29]),
	.A(n_40));
   sky130_osu_sc_18T_ms__inv_l g7616 (.Y(ext_mem_dat_o[6]),
	.A(n_42));
   sky130_osu_sc_18T_ms__inv_l g7558 (.Y(ext_mem_dat_o[19]),
	.A(n_76));
   sky130_osu_sc_18T_ms__inv_l g7559 (.Y(ext_mem_dat_o[18]),
	.A(n_72));
   sky130_osu_sc_18T_ms__inv_l g7538 (.Y(ext_mem_adr_o[8]),
	.A(n_73));
   sky130_osu_sc_18T_ms__inv_l g7560 (.Y(ext_mem_dat_o[17]),
	.A(n_71));
   sky130_osu_sc_18T_ms__inv_l g7561 (.Y(ext_mem_adr_o[30]),
	.A(n_69));
   sky130_osu_sc_18T_ms__inv_l g7539 (.Y(ext_mem_adr_o[7]),
	.A(n_70));
   sky130_osu_sc_18T_ms__inv_l g7562 (.Y(ext_mem_dat_o[16]),
	.A(n_68));
   sky130_osu_sc_18T_ms__inv_l g7537 (.Y(ext_mem_adr_o[9]),
	.A(n_81));
   sky130_osu_sc_18T_ms__inv_l g7540 (.Y(ext_mem_adr_o[6]),
	.A(n_67));
   sky130_osu_sc_18T_ms__inv_l g7601 (.Y(ext_mem_dat_o[4]),
	.A(n_66));
   sky130_osu_sc_18T_ms__inv_l g7602 (.Y(ext_mem_adr_o[28]),
	.A(n_64));
   sky130_osu_sc_18T_ms__inv_l g7541 (.Y(ext_mem_adr_o[5]),
	.A(n_65));
   sky130_osu_sc_18T_ms__inv_l g7603 (.Y(ext_mem_dat_o[13]),
	.A(n_63));
   sky130_osu_sc_18T_ms__inv_l g7604 (.Y(ext_mem_adr_o[27]),
	.A(n_61));
   sky130_osu_sc_18T_ms__inv_l g7542 (.Y(ext_mem_adr_o[4]),
	.A(n_62));
   sky130_osu_sc_18T_ms__inv_l g7605 (.Y(ext_mem_dat_o[12]),
	.A(n_60));
   sky130_osu_sc_18T_ms__inv_l g7606 (.Y(ext_mem_adr_o[26]),
	.A(n_58));
   sky130_osu_sc_18T_ms__inv_l g7543 (.Y(ext_mem_adr_o[3]),
	.A(n_59));
   sky130_osu_sc_18T_ms__inv_l g7607 (.Y(ext_mem_dat_o[11]),
	.A(n_57));
   sky130_osu_sc_18T_ms__inv_l g7608 (.Y(ext_mem_dat_o[10]),
	.A(n_55));
   sky130_osu_sc_18T_ms__inv_l g7544 (.Y(ext_mem_adr_o[2]),
	.A(n_74));
   sky130_osu_sc_18T_ms__inv_l g7609 (.Y(ext_mem_adr_o[25]),
	.A(n_53));
   sky130_osu_sc_18T_ms__inv_l g7610 (.Y(ext_mem_dat_o[9]),
	.A(n_51));
   sky130_osu_sc_18T_ms__inv_l g7545 (.Y(ext_mem_adr_o[1]),
	.A(n_52));
   sky130_osu_sc_18T_ms__inv_l g7531 (.Y(ext_mem_dat_o[30]),
	.A(n_54));
   sky130_osu_sc_18T_ms__inv_l g7611 (.Y(ext_mem_adr_o[24]),
	.A(n_50));
   sky130_osu_sc_18T_ms__inv_l g7612 (.Y(ext_mem_dat_o[8]),
	.A(n_48));
   sky130_osu_sc_18T_ms__inv_l g7546 (.Y(ext_mem_adr_o[0]),
	.A(n_49));
   sky130_osu_sc_18T_ms__inv_l g7613 (.Y(ext_mem_adr_o[23]),
	.A(n_46));
   sky130_osu_sc_18T_ms__inv_l g7614 (.Y(ext_mem_dat_o[7]),
	.A(n_44));
   sky130_osu_sc_18T_ms__inv_l g7547 (.Y(ext_mem_dat_o[31]),
	.A(n_45));
   sky130_osu_sc_18T_ms__inv_l g7532 (.Y(ext_mem_dat_o[15]),
	.A(n_47));
   sky130_osu_sc_18T_ms__inv_l g7615 (.Y(ext_mem_adr_o[22]),
	.A(n_43));
   sky130_osu_sc_18T_ms__aoi22_l g7585__9945 (.Y(n_110),
	.A0(iwb_dat_i[28]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[28]));
   sky130_osu_sc_18T_ms__aoi22_l g7655__2883 (.Y(n_109),
	.A0(iwb_dat_i[14]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[14]));
   sky130_osu_sc_18T_ms__aoi22_l g7657__2346 (.Y(n_106),
	.A0(iwb_adr_i[19]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[19]));
   sky130_osu_sc_18T_ms__aoi22_l g7586__1666 (.Y(n_105),
	.A0(iwb_dat_i[27]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[27]));
   sky130_osu_sc_18T_ms__aoi22_l g7656__7410 (.Y(n_104),
	.A0(iwb_adr_i[20]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[20]));
   sky130_osu_sc_18T_ms__nand2_l g7673__6417 (.Y(ext_mem_adr_o[31]),
	.A(n_33),
	.B(n_36));
   sky130_osu_sc_18T_ms__aoi22_l g7658__5477 (.Y(n_102),
	.A0(iwb_dat_i[3]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[3]));
   sky130_osu_sc_18T_ms__aoi22_l g7659__2398 (.Y(n_101),
	.A0(iwb_dat_i[2]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[2]));
   sky130_osu_sc_18T_ms__aoi22_l g7587__5107 (.Y(n_100),
	.A0(iwb_dat_i[26]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[26]));
   sky130_osu_sc_18T_ms__aoi22_l g7569__6260 (.Y(n_99),
	.A0(iwb_adr_i[12]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[12]));
   sky130_osu_sc_18T_ms__aoi22_l g7660__4319 (.Y(n_98),
	.A0(iwb_adr_i[18]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[18]));
   sky130_osu_sc_18T_ms__aoi22_l g7588__8428 (.Y(n_97),
	.A0(iwb_dat_i[25]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[25]));
   sky130_osu_sc_18T_ms__aoi22_l g7661__5526 (.Y(n_96),
	.A0(iwb_dat_i[1]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[1]));
   sky130_osu_sc_18T_ms__aoi22_l g7570__6783 (.Y(n_95),
	.A0(iwb_adr_i[11]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[11]));
   sky130_osu_sc_18T_ms__aoi22_l g7662__3680 (.Y(n_94),
	.A0(iwb_adr_i[17]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[17]));
   sky130_osu_sc_18T_ms__aoi22_l g7589__1617 (.Y(n_93),
	.A0(iwb_dat_i[24]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[24]));
   sky130_osu_sc_18T_ms__aoi22_l g7663__2802 (.Y(n_92),
	.A0(iwb_dat_i[0]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[0]));
   sky130_osu_sc_18T_ms__aoi22_l g7664__1705 (.Y(n_91),
	.A0(iwb_adr_i[16]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[16]));
   sky130_osu_sc_18T_ms__aoi22_l g7590__5122 (.Y(n_90),
	.A0(iwb_dat_i[23]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[23]));
   sky130_osu_sc_18T_ms__aoi22_l g7665__8246 (.Y(n_89),
	.A0(iwb_we_i),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_we_i));
   sky130_osu_sc_18T_ms__aoi22_l g7571__7098 (.Y(n_88),
	.A0(iwb_adr_i[10]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[10]));
   sky130_osu_sc_18T_ms__aoi22_l g7666__6131 (.Y(n_87),
	.A0(iwb_adr_i[15]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[15]));
   sky130_osu_sc_18T_ms__aoi22_l g7591__1881 (.Y(n_86),
	.A0(iwb_dat_i[22]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[22]));
   sky130_osu_sc_18T_ms__aoi22_l g7667__5115 (.Y(n_85),
	.A0(iwb_sel_i[3]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_sel_i[3]));
   sky130_osu_sc_18T_ms__aoi22_l g7668__7482 (.Y(n_84),
	.A0(iwb_sel_i[2]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_sel_i[2]));
   sky130_osu_sc_18T_ms__aoi22_l g7592__4733 (.Y(n_83),
	.A0(iwb_dat_i[21]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[21]));
   sky130_osu_sc_18T_ms__aoi22_l g7669__6161 (.Y(n_82),
	.A0(iwb_adr_i[14]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[14]));
   sky130_osu_sc_18T_ms__aoi22_l g7572__9315 (.Y(n_81),
	.A0(iwb_adr_i[9]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[9]));
   sky130_osu_sc_18T_ms__aoi22_l g7670__9945 (.Y(n_80),
	.A0(iwb_sel_i[1]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_sel_i[1]));
   sky130_osu_sc_18T_ms__aoi22_l g7593__2883 (.Y(n_79),
	.A0(iwb_dat_i[20]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[20]));
   sky130_osu_sc_18T_ms__aoi22_l g7671__2346 (.Y(n_78),
	.A0(iwb_sel_i[0]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_sel_i[0]));
   sky130_osu_sc_18T_ms__aoi22_l g7672__1666 (.Y(n_77),
	.A0(iwb_adr_i[13]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[13]));
   sky130_osu_sc_18T_ms__aoi22_l g7594__7410 (.Y(n_76),
	.A0(iwb_dat_i[19]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[19]));
   sky130_osu_sc_18T_ms__aoi22_l g7654__6417 (.Y(n_75),
	.A0(iwb_dat_i[5]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[5]));
   sky130_osu_sc_18T_ms__dffr_1 ext_ack_reg (.Q(UNCONNECTED1),
	.QN(ext_ack),
	.CK(clk),
	.D(n_37),
	.RN(rst_n));
   sky130_osu_sc_18T_ms__aoi22_l g7579__5477 (.Y(n_74),
	.A0(iwb_adr_i[2]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[2]));
   sky130_osu_sc_18T_ms__aoi22_l g7573__2398 (.Y(n_73),
	.A0(iwb_adr_i[8]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[8]));
   sky130_osu_sc_18T_ms__aoi22_l g7595__5107 (.Y(n_72),
	.A0(iwb_dat_i[18]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[18]));
   sky130_osu_sc_18T_ms__aoi22_l g7596__6260 (.Y(n_71),
	.A0(iwb_dat_i[17]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[17]));
   sky130_osu_sc_18T_ms__aoi22_l g7574__4319 (.Y(n_70),
	.A0(iwb_adr_i[7]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[7]));
   sky130_osu_sc_18T_ms__aoi22_l g7597__8428 (.Y(n_69),
	.A0(iwb_adr_i[30]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[30]));
   sky130_osu_sc_18T_ms__aoi22_l g7598__5526 (.Y(n_68),
	.A0(iwb_dat_i[16]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[16]));
   sky130_osu_sc_18T_ms__aoi22_l g7575__6783 (.Y(n_67),
	.A0(iwb_adr_i[6]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[6]));
   sky130_osu_sc_18T_ms__aoi22_l g7637__3680 (.Y(n_66),
	.A0(iwb_dat_i[4]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[4]));
   sky130_osu_sc_18T_ms__aoi22_l g7576__1617 (.Y(n_65),
	.A0(iwb_adr_i[5]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[5]));
   sky130_osu_sc_18T_ms__aoi22_l g7638__2802 (.Y(n_64),
	.A0(iwb_adr_i[28]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[28]));
   sky130_osu_sc_18T_ms__aoi22_l g7639__1705 (.Y(n_63),
	.A0(iwb_dat_i[13]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[13]));
   sky130_osu_sc_18T_ms__aoi22_l g7577__5122 (.Y(n_62),
	.A0(iwb_adr_i[4]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[4]));
   sky130_osu_sc_18T_ms__aoi22_l g7640__8246 (.Y(n_61),
	.A0(iwb_adr_i[27]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[27]));
   sky130_osu_sc_18T_ms__aoi22_l g7641__7098 (.Y(n_60),
	.A0(iwb_dat_i[12]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[12]));
   sky130_osu_sc_18T_ms__aoi22_l g7578__6131 (.Y(n_59),
	.A0(iwb_adr_i[3]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[3]));
   sky130_osu_sc_18T_ms__aoi22_l g7642__1881 (.Y(n_58),
	.A0(iwb_adr_i[26]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[26]));
   sky130_osu_sc_18T_ms__aoi22_l g7643__5115 (.Y(n_57),
	.A0(iwb_dat_i[11]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[11]));
   sky130_osu_sc_18T_ms__aoi22_l g7653__7482 (.Y(n_56),
	.A0(iwb_adr_i[21]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[21]));
   sky130_osu_sc_18T_ms__aoi22_l g7644__4733 (.Y(n_55),
	.A0(iwb_dat_i[10]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[10]));
   sky130_osu_sc_18T_ms__aoi22_l g7565__6161 (.Y(n_54),
	.A0(iwb_dat_i[30]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[30]));
   sky130_osu_sc_18T_ms__aoi22_l g7645__9315 (.Y(n_53),
	.A0(iwb_adr_i[25]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[25]));
   sky130_osu_sc_18T_ms__aoi22_l g7580__9945 (.Y(n_52),
	.A0(iwb_adr_i[1]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[1]));
   sky130_osu_sc_18T_ms__aoi22_l g7646__2883 (.Y(n_51),
	.A0(iwb_dat_i[9]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[9]));
   sky130_osu_sc_18T_ms__aoi22_l g7647__2346 (.Y(n_50),
	.A0(iwb_adr_i[24]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[24]));
   sky130_osu_sc_18T_ms__aoi22_l g7581__1666 (.Y(n_49),
	.A0(iwb_adr_i[0]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[0]));
   sky130_osu_sc_18T_ms__aoi22_l g7648__7410 (.Y(n_48),
	.A0(iwb_dat_i[8]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[8]));
   sky130_osu_sc_18T_ms__aoi22_l g7566__6417 (.Y(n_47),
	.A0(iwb_dat_i[15]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[15]));
   sky130_osu_sc_18T_ms__aoi22_l g7649__5477 (.Y(n_46),
	.A0(iwb_adr_i[23]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[23]));
   sky130_osu_sc_18T_ms__aoi22_l g7582__2398 (.Y(n_45),
	.A0(iwb_dat_i[31]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[31]));
   sky130_osu_sc_18T_ms__aoi22_l g7650__5107 (.Y(n_44),
	.A0(iwb_dat_i[7]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[7]));
   sky130_osu_sc_18T_ms__aoi22_l g7651__6260 (.Y(n_43),
	.A0(iwb_adr_i[22]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[22]));
   sky130_osu_sc_18T_ms__aoi22_l g7652__4319 (.Y(n_42),
	.A0(iwb_dat_i[6]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[6]));
   sky130_osu_sc_18T_ms__aoi22_l g7567__8428 (.Y(n_41),
	.A0(iwb_adr_i[29]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_adr_i[29]));
   sky130_osu_sc_18T_ms__aoi22_l g7584__5526 (.Y(n_40),
	.A0(iwb_dat_i[29]),
	.A1(n_108),
	.B0(n_107),
	.B1(dwb_dat_i[29]));
   sky130_osu_sc_18T_ms__inv_1 g7675 (.Y(n_181),
	.A(n_39));
   sky130_osu_sc_18T_ms__nor2_1 g7676__6783 (.Y(n_38),
	.A(n_30),
	.B(n_34));
   sky130_osu_sc_18T_ms__nand2_1 g7677__3680 (.Y(n_39),
	.A(n_31),
	.B(n_35));
   sky130_osu_sc_18T_ms__and2_l g7682__1617 (.Y(iwb_err_o),
	.A(ext_mem_cyc_o),
	.B(ext_mem_err_i));
   sky130_osu_sc_18T_ms__and2_1 g7678__2802 (.Y(n_37),
	.A(ext_mem_cyc_o),
	.B(ext_mem_ack_i));
   sky130_osu_sc_18T_ms__aoi21_l g7681__1705 (.Y(n_36),
	.A0(iwb_adr_i[31]),
	.A1(n_32),
	.B0(n_27));
   sky130_osu_sc_18T_ms__nor2_1 g7680__5122 (.Y(n_35),
	.A(n_21),
	.B(n_28));
   sky130_osu_sc_18T_ms__nand2_1 g7679__8246 (.Y(n_34),
	.A(n_10),
	.B(n_29));
   sky130_osu_sc_18T_ms__inv_l g7687 (.Y(n_33),
	.A(n_107));
   sky130_osu_sc_18T_ms__oai21_l g7683__7098 (.Y(n_108),
	.A0(n_1),
	.A1(n_193),
	.B0(n_190));
   sky130_osu_sc_18T_ms__nor2_1 g7690__6131 (.Y(n_107),
	.A(iwb_cyc_i),
	.B(n_193));
   sky130_osu_sc_18T_ms__nand2_1 g7689__1881 (.Y(ext_mem_cyc_o),
	.A(n_193),
	.B(n_190));
   sky130_osu_sc_18T_ms__inv_1 g7692 (.Y(n_32),
	.A(n_193));
   sky130_osu_sc_18T_ms__nor2_1 g7684__5115 (.Y(n_31),
	.A(n_25),
	.B(n_22));
   sky130_osu_sc_18T_ms__nand2_1 g7685__7482 (.Y(n_30),
	.A(n_26),
	.B(n_20));
   sky130_osu_sc_18T_ms__nor2_1 g7686__4733 (.Y(n_29),
	.A(n_9),
	.B(n_23));
   sky130_osu_sc_18T_ms__nand2_1 g7688__6161 (.Y(n_28),
	.A(n_5),
	.B(n_24));
   sky130_osu_sc_18T_ms__inv_1 g7691 (.Y(n_27),
	.A(n_190));
   sky130_osu_sc_18T_ms__nand2_1 g7696__9315 (.Y(n_190),
	.A(iwb_adr_i[31]),
	.B(n_15));
   sky130_osu_sc_18T_ms__nand2_1 g7697__9945 (.Y(n_193),
	.A(dwb_adr_i[31]),
	.B(n_17));
   sky130_osu_sc_18T_ms__nor2_l g7695__2883 (.Y(n_26),
	.A(dwb_adr_i[17]),
	.B(n_16));
   sky130_osu_sc_18T_ms__or2_1 g7694__2346 (.Y(n_25),
	.A(iwb_adr_i[16]),
	.B(n_4));
   sky130_osu_sc_18T_ms__nor2_1 g7693__1666 (.Y(n_24),
	.A(iwb_adr_i[23]),
	.B(n_3));
   sky130_osu_sc_18T_ms__nand2_1 g7699__7410 (.Y(n_23),
	.A(n_7),
	.B(n_14));
   sky130_osu_sc_18T_ms__nand2_1 g7702__6417 (.Y(n_22),
	.A(n_6),
	.B(n_2));
   sky130_osu_sc_18T_ms__nand2_1 g7701__5477 (.Y(n_21),
	.A(n_8),
	.B(n_13));
   sky130_osu_sc_18T_ms__and2_1 g7700__2398 (.Y(n_20),
	.A(n_11),
	.B(n_12));
   sky130_osu_sc_18T_ms__nor2_1 g7698__5107 (.Y(n_19),
	.A(iwb_adr_i[31]),
	.B(n_173));
   sky130_osu_sc_18T_ms__inv_1 g7711 (.Y(n_17),
	.A(n_16));
   sky130_osu_sc_18T_ms__inv_1 g7712 (.Y(n_15),
	.A(n_173));
   sky130_osu_sc_18T_ms__nor2_1 g7710__4319 (.Y(n_14),
	.A(dwb_adr_i[24]),
	.B(dwb_adr_i[25]));
   sky130_osu_sc_18T_ms__nor2_1 g7704__8428 (.Y(n_13),
	.A(iwb_adr_i[20]),
	.B(iwb_adr_i[27]));
   sky130_osu_sc_18T_ms__nor2_1 g7705__5526 (.Y(n_12),
	.A(dwb_adr_i[27]),
	.B(dwb_adr_i[30]));
   sky130_osu_sc_18T_ms__nor2_1 g7706__6783 (.Y(n_11),
	.A(dwb_adr_i[21]),
	.B(dwb_adr_i[22]));
   sky130_osu_sc_18T_ms__nor2_1 g7708__3680 (.Y(n_10),
	.A(dwb_adr_i[23]),
	.B(dwb_adr_i[26]));
   sky130_osu_sc_18T_ms__or2_1 g7709__1617 (.Y(n_9),
	.A(dwb_adr_i[16]),
	.B(dwb_adr_i[19]));
   sky130_osu_sc_18T_ms__nor2_1 g7703__2802 (.Y(n_8),
	.A(iwb_adr_i[17]),
	.B(iwb_adr_i[28]));
   sky130_osu_sc_18T_ms__nor2_1 g7717__1705 (.Y(n_7),
	.A(dwb_adr_i[18]),
	.B(dwb_adr_i[20]));
   sky130_osu_sc_18T_ms__nor2_1 g7714__5122 (.Y(n_6),
	.A(iwb_adr_i[18]),
	.B(iwb_adr_i[26]));
   sky130_osu_sc_18T_ms__nor2_1 g7715__8246 (.Y(n_5),
	.A(iwb_adr_i[21]),
	.B(iwb_adr_i[29]));
   sky130_osu_sc_18T_ms__or2_1 g7716__7098 (.Y(n_4),
	.A(iwb_adr_i[19]),
	.B(iwb_adr_i[30]));
   sky130_osu_sc_18T_ms__or2_1 g7713__6131 (.Y(n_3),
	.A(iwb_adr_i[15]),
	.B(iwb_adr_i[24]));
   sky130_osu_sc_18T_ms__nor2_1 g7718__1881 (.Y(n_2),
	.A(iwb_adr_i[22]),
	.B(iwb_adr_i[25]));
   sky130_osu_sc_18T_ms__nand2_1 g7719__5115 (.Y(n_16),
	.A(dwb_stb_i),
	.B(dwb_cyc_i));
   sky130_osu_sc_18T_ms__nand2_1 g7720__7482 (.Y(n_173),
	.A(iwb_stb_i),
	.B(iwb_cyc_i));
   sky130_osu_sc_18T_ms__inv_1 g7722 (.Y(n_1),
	.A(iwb_cyc_i));
   sky130_osu_sc_18T_ms__or2_1 g2 (.Y(n_448),
	.A(n_447),
	.B(dwb_adr_i[28]));
   sky130_osu_sc_18T_ms__nand2_1 g3 (.Y(n_447),
	.A(dwb_adr_i[29]),
	.B(n_38));
endmodule

