###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID pc231.ee.hacettepe.edu.tr)
#  Generated on:      Thu Dec 25 15:19:02 2025
#  Design:            rv32im_soc_with_integrated_core
###############################################################
current_design rv32im_soc_with_integrated_core
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_propagated_clock  [get_ports {clk}]
set_wire_load_mode enclosed
set_clock_uncertainty 0.1 [get_clocks {clk}]
