/*
###############################################################
#  Generated by:      Cadence Innovus 21.35-s114_1
#  OS:                Linux x86_64(Host ID pc231.ee.hacettepe.edu.tr)
#  Generated on:      Thu Dec 25 15:19:02 2025
#  Design:            rv32im_soc_with_integrated_core
#  Command:           saveNetlist outputs/soc_integrated/rv32im_soc_with_integrated_core_netlist.v -excludeLeafCell
###############################################################
*/
module rv32im_soc_with_integrated_core (
	clk, 
	rst_n, 
	ext_mem_adr_o, 
	ext_mem_dat_o, 
	ext_mem_dat_i, 
	ext_mem_we_o, 
	ext_mem_sel_o, 
	ext_mem_cyc_o, 
	ext_mem_stb_o, 
	ext_mem_ack_i, 
	ext_mem_err_i, 
	uart_tx, 
	uart_rx, 
	spi_sclk, 
	spi_mosi, 
	spi_miso, 
	spi_cs_n, 
	gpio, 
	pwm_out, 
	pwm_out_n, 
	adc_data_in, 
	adc_clk_out, 
	ch0_data, 
	ch1_data, 
	ch2_data, 
	ch3_data, 
	adc_data_valid, 
	current_sense, 
	voltage_sense, 
	thermal_alert_in, 
	emergency_stop, 
	channel_disable, 
	system_reset, 
	watchdog_timeout, 
	timer_interrupt, 
	timer_compare_out, 
	ext_interrupts);
   input clk;
   input rst_n;
   output [31:0] ext_mem_adr_o;
   output [31:0] ext_mem_dat_o;
   input [31:0] ext_mem_dat_i;
   output ext_mem_we_o;
   output [3:0] ext_mem_sel_o;
   output ext_mem_cyc_o;
   output ext_mem_stb_o;
   input ext_mem_ack_i;
   input ext_mem_err_i;
   output uart_tx;
   input uart_rx;
   output spi_sclk;
   output spi_mosi;
   input spi_miso;
   output spi_cs_n;
   inout [15:0] gpio;
   output [7:0] pwm_out;
   output [7:0] pwm_out_n;
   input [3:0] adc_data_in;
   output [3:0] adc_clk_out;
   output [15:0] ch0_data;
   output [15:0] ch1_data;
   output [15:0] ch2_data;
   output [15:0] ch3_data;
   output [3:0] adc_data_valid;
   input [3:0] current_sense;
   input [3:0] voltage_sense;
   input thermal_alert_in;
   output emergency_stop;
   output [3:0] channel_disable;
   output system_reset;
   output watchdog_timeout;
   output timer_interrupt;
   output [3:0] timer_compare_out;
   input [7:0] ext_interrupts;

   // Internal wires
   wire FE_OFN5_prot_sel;
   wire FE_OFN4_comm_sel;
   wire FE_OFN3_adc_sel;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire CTS_7;
   wire CTS_6;
   wire FE_OFN3_n_482;
   wire FE_OFN2_n_428;
   wire [31:0] adc_wb_dat_miso;
   wire [31:0] comm_wb_dat_miso;
   wire [31:0] iwb_dat_miso;
   wire [31:0] iwb_adr;
   wire [31:0] dwb_adr;
   wire [31:0] dwb_dat_mosi;
   wire [3:0] dwb_sel;
   wire [31:0] mem_wb_dat_miso;
   wire [31:0] prot_wb_dat_miso;
   wire [31:0] pwm_wb_dat_miso;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire UNCONNECTED31;
   wire UNCONNECTED32;
   wire UNCONNECTED33;
   wire UNCONNECTED34;
   wire UNCONNECTED35;
   wire UNCONNECTED36;
   wire UNCONNECTED37;
   wire UNCONNECTED38;
   wire UNCONNECTED39;
   wire UNCONNECTED40;
   wire UNCONNECTED41;
   wire UNCONNECTED42;
   wire UNCONNECTED43;
   wire UNCONNECTED44;
   wire UNCONNECTED45;
   wire UNCONNECTED46;
   wire UNCONNECTED47;
   wire UNCONNECTED48;
   wire UNCONNECTED49;
   wire UNCONNECTED50;
   wire UNCONNECTED51;
   wire UNCONNECTED52;
   wire UNCONNECTED53;
   wire UNCONNECTED54;
   wire UNCONNECTED55;
   wire UNCONNECTED56;
   wire UNCONNECTED57;
   wire UNCONNECTED58;
   wire UNCONNECTED59;
   wire UNCONNECTED60;
   wire UNCONNECTED61;
   wire UNCONNECTED62;
   wire UNCONNECTED63;
   wire UNCONNECTED64;
   wire UNCONNECTED65;
   wire UNCONNECTED66;
   wire UNCONNECTED67;
   wire UNCONNECTED68;
   wire UNCONNECTED69;
   wire UNCONNECTED70;
   wire UNCONNECTED71;
   wire UNCONNECTED72;
   wire UNCONNECTED73;
   wire UNCONNECTED74;
   wire UNCONNECTED75;
   wire UNCONNECTED76;
   wire UNCONNECTED77;
   wire UNCONNECTED78;
   wire UNCONNECTED79;
   wire UNCONNECTED80;
   wire UNCONNECTED81;
   wire UNCONNECTED82;
   wire UNCONNECTED83;
   wire UNCONNECTED84;
   wire UNCONNECTED85;
   wire UNCONNECTED86;
   wire UNCONNECTED87;
   wire UNCONNECTED88;
   wire UNCONNECTED89;
   wire UNCONNECTED90;
   wire UNCONNECTED91;
   wire UNCONNECTED92;
   wire UNCONNECTED93;
   wire UNCONNECTED94;
   wire UNCONNECTED95;
   wire UNCONNECTED96;
   wire UNCONNECTED97;
   wire UNCONNECTED98;
   wire UNCONNECTED99;
   wire UNCONNECTED100;
   wire UNCONNECTED101;
   wire UNCONNECTED102;
   wire UNCONNECTED103;
   wire UNCONNECTED104;
   wire UNCONNECTED105;
   wire UNCONNECTED106;
   wire UNCONNECTED107;
   wire UNCONNECTED108;
   wire UNCONNECTED109;
   wire UNCONNECTED110;
   wire UNCONNECTED111;
   wire UNCONNECTED112;
   wire UNCONNECTED113;
   wire UNCONNECTED114;
   wire UNCONNECTED115;
   wire UNCONNECTED116;
   wire UNCONNECTED117;
   wire UNCONNECTED118;
   wire UNCONNECTED119;
   wire UNCONNECTED120;
   wire UNCONNECTED121;
   wire UNCONNECTED122;
   wire UNCONNECTED123;
   wire UNCONNECTED124;
   wire UNCONNECTED125;
   wire UNCONNECTED126;
   wire UNCONNECTED127;
   wire UNCONNECTED128;
   wire UNCONNECTED129;
   wire UNCONNECTED130;
   wire UNCONNECTED131;
   wire UNCONNECTED132;
   wire UNCONNECTED133;
   wire UNCONNECTED134;
   wire UNCONNECTED135;
   wire UNCONNECTED136;
   wire UNCONNECTED137;
   wire UNCONNECTED138;
   wire UNCONNECTED139;
   wire UNCONNECTED140;
   wire UNCONNECTED141;
   wire UNCONNECTED142;
   wire UNCONNECTED143;
   wire UNCONNECTED144;
   wire UNCONNECTED145;
   wire UNCONNECTED146;
   wire UNCONNECTED147;
   wire UNCONNECTED148;
   wire UNCONNECTED149;
   wire UNCONNECTED150;
   wire UNCONNECTED151;
   wire UNCONNECTED152;
   wire UNCONNECTED153;
   wire UNCONNECTED154;
   wire UNCONNECTED155;
   wire UNCONNECTED156;
   wire UNCONNECTED157;
   wire UNCONNECTED158;
   wire UNCONNECTED159;
   wire UNCONNECTED160;
   wire UNCONNECTED161;
   wire UNCONNECTED162;
   wire UNCONNECTED163;
   wire UNCONNECTED164;
   wire UNCONNECTED165;
   wire UNCONNECTED166;
   wire UNCONNECTED167;
   wire UNCONNECTED168;
   wire UNCONNECTED169;
   wire UNCONNECTED170;
   wire UNCONNECTED171;
   wire UNCONNECTED172;
   wire UNCONNECTED173;
   wire UNCONNECTED174;
   wire UNCONNECTED175;
   wire UNCONNECTED176;
   wire UNCONNECTED177;
   wire UNCONNECTED178;
   wire UNCONNECTED179;
   wire UNCONNECTED180;
   wire UNCONNECTED181;
   wire UNCONNECTED182;
   wire UNCONNECTED183;
   wire UNCONNECTED184;
   wire UNCONNECTED185;
   wire UNCONNECTED186;
   wire UNCONNECTED187;
   wire UNCONNECTED188;
   wire UNCONNECTED189;
   wire UNCONNECTED190;
   wire UNCONNECTED191;
   wire UNCONNECTED192;
   wire UNCONNECTED193;
   wire UNCONNECTED194;
   wire UNCONNECTED195;
   wire UNCONNECTED196;
   wire UNCONNECTED197;
   wire UNCONNECTED198;
   wire UNCONNECTED199;
   wire UNCONNECTED200;
   wire UNCONNECTED201;
   wire adc_irq;
   wire adc_sel;
   wire adc_wb_ack;
   wire adc_wb_err;
   wire comm_irq;
   wire comm_sel;
   wire comm_wb_ack;
   wire comm_wb_err;
   wire dwb_cyc;
   wire dwb_stb;
   wire dwb_we;
   wire iwb_ack;
   wire iwb_cyc;
   wire iwb_stb;
   wire mem_wb_ack;
   wire mem_wb_err;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_318;
   wire n_319;
   wire n_320;
   wire n_321;
   wire n_322;
   wire n_323;
   wire n_324;
   wire n_325;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_346;
   wire n_347;
   wire n_348;
   wire n_349;
   wire n_350;
   wire n_351;
   wire n_352;
   wire n_353;
   wire n_354;
   wire n_355;
   wire n_356;
   wire n_357;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_361;
   wire n_362;
   wire n_363;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_367;
   wire n_368;
   wire n_369;
   wire n_370;
   wire n_375;
   wire n_376;
   wire n_377;
   wire n_378;
   wire n_379;
   wire n_380;
   wire n_381;
   wire n_382;
   wire n_383;
   wire n_384;
   wire n_385;
   wire n_386;
   wire n_387;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_394;
   wire n_395;
   wire n_396;
   wire n_397;
   wire n_398;
   wire n_399;
   wire n_400;
   wire n_401;
   wire n_402;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_408;
   wire n_409;
   wire n_410;
   wire n_411;
   wire n_412;
   wire n_413;
   wire n_414;
   wire n_415;
   wire n_416;
   wire n_417;
   wire n_418;
   wire n_419;
   wire n_420;
   wire n_421;
   wire n_422;
   wire n_423;
   wire n_424;
   wire n_425;
   wire n_426;
   wire n_427;
   wire n_428;
   wire n_429;
   wire n_430;
   wire n_431;
   wire n_432;
   wire n_433;
   wire n_434;
   wire n_435;
   wire n_436;
   wire n_437;
   wire n_438;
   wire n_439;
   wire n_440;
   wire n_441;
   wire n_442;
   wire n_443;
   wire n_444;
   wire n_445;
   wire n_446;
   wire n_447;
   wire n_448;
   wire n_449;
   wire n_450;
   wire n_451;
   wire n_452;
   wire n_453;
   wire n_454;
   wire n_455;
   wire n_456;
   wire n_457;
   wire n_458;
   wire n_459;
   wire n_460;
   wire n_461;
   wire n_462;
   wire n_463;
   wire n_464;
   wire n_465;
   wire n_466;
   wire n_467;
   wire n_468;
   wire n_469;
   wire n_470;
   wire n_471;
   wire n_472;
   wire n_473;
   wire n_474;
   wire n_475;
   wire n_476;
   wire n_477;
   wire n_478;
   wire n_479;
   wire n_480;
   wire n_481;
   wire n_482;
   wire n_483;
   wire n_484;
   wire n_485;
   wire n_486;
   wire n_487;
   wire n_488;
   wire n_489;
   wire n_490;
   wire n_491;
   wire n_492;
   wire n_493;
   wire n_494;
   wire n_495;
   wire n_496;
   wire n_497;
   wire n_498;
   wire n_499;
   wire n_500;
   wire n_501;
   wire n_502;
   wire n_503;
   wire n_504;
   wire n_505;
   wire n_506;
   wire n_507;
   wire n_508;
   wire n_509;
   wire n_510;
   wire n_511;
   wire n_512;
   wire n_513;
   wire n_514;
   wire n_515;
   wire n_516;
   wire n_517;
   wire n_518;
   wire n_519;
   wire n_520;
   wire n_521;
   wire n_522;
   wire n_523;
   wire n_524;
   wire n_525;
   wire n_526;
   wire n_527;
   wire n_528;
   wire n_529;
   wire n_530;
   wire n_531;
   wire n_532;
   wire n_533;
   wire n_534;
   wire n_535;
   wire n_536;
   wire n_537;
   wire n_538;
   wire n_539;
   wire n_540;
   wire n_541;
   wire n_542;
   wire n_543;
   wire n_544;
   wire n_545;
   wire n_546;
   wire n_547;
   wire n_548;
   wire n_549;
   wire n_550;
   wire n_551;
   wire n_552;
   wire n_553;
   wire n_554;
   wire n_555;
   wire n_556;
   wire n_557;
   wire n_558;
   wire n_559;
   wire n_560;
   wire n_561;
   wire n_562;
   wire n_563;
   wire n_564;
   wire n_565;
   wire n_566;
   wire n_567;
   wire n_568;
   wire n_569;
   wire n_570;
   wire n_571;
   wire n_572;
   wire n_573;
   wire n_574;
   wire n_575;
   wire n_576;
   wire n_577;
   wire n_578;
   wire n_579;
   wire n_580;
   wire n_581;
   wire n_582;
   wire n_583;
   wire prot_irq;
   wire prot_sel;
   wire prot_wb_ack;
   wire prot_wb_err;
   wire pwm_irq;
   wire pwm_wb_ack;
   wire pwm_wb_err;

   assign timer_compare_out[0] = 1'b0 ;
   assign timer_compare_out[1] = 1'b0 ;
   assign timer_compare_out[2] = 1'b0 ;
   assign timer_compare_out[3] = 1'b0 ;
   assign timer_interrupt = 1'b0 ;
   assign ext_mem_stb_o = 1'b0 ;
   assign ext_mem_cyc_o = 1'b0 ;
   assign ext_mem_sel_o[0] = 1'b0 ;
   assign ext_mem_sel_o[1] = 1'b0 ;
   assign ext_mem_sel_o[2] = 1'b0 ;
   assign ext_mem_sel_o[3] = 1'b0 ;
   assign ext_mem_we_o = 1'b0 ;
   assign ext_mem_dat_o[0] = 1'b0 ;
   assign ext_mem_dat_o[1] = 1'b0 ;
   assign ext_mem_dat_o[2] = 1'b0 ;
   assign ext_mem_dat_o[3] = 1'b0 ;
   assign ext_mem_dat_o[4] = 1'b0 ;
   assign ext_mem_dat_o[5] = 1'b0 ;
   assign ext_mem_dat_o[6] = 1'b0 ;
   assign ext_mem_dat_o[7] = 1'b0 ;
   assign ext_mem_dat_o[8] = 1'b0 ;
   assign ext_mem_dat_o[9] = 1'b0 ;
   assign ext_mem_dat_o[10] = 1'b0 ;
   assign ext_mem_dat_o[11] = 1'b0 ;
   assign ext_mem_dat_o[12] = 1'b0 ;
   assign ext_mem_dat_o[13] = 1'b0 ;
   assign ext_mem_dat_o[14] = 1'b0 ;
   assign ext_mem_dat_o[15] = 1'b0 ;
   assign ext_mem_dat_o[16] = 1'b0 ;
   assign ext_mem_dat_o[17] = 1'b0 ;
   assign ext_mem_dat_o[18] = 1'b0 ;
   assign ext_mem_dat_o[19] = 1'b0 ;
   assign ext_mem_dat_o[20] = 1'b0 ;
   assign ext_mem_dat_o[21] = 1'b0 ;
   assign ext_mem_dat_o[22] = 1'b0 ;
   assign ext_mem_dat_o[23] = 1'b0 ;
   assign ext_mem_dat_o[24] = 1'b0 ;
   assign ext_mem_dat_o[25] = 1'b0 ;
   assign ext_mem_dat_o[26] = 1'b0 ;
   assign ext_mem_dat_o[27] = 1'b0 ;
   assign ext_mem_dat_o[28] = 1'b0 ;
   assign ext_mem_dat_o[29] = 1'b0 ;
   assign ext_mem_dat_o[30] = 1'b0 ;
   assign ext_mem_dat_o[31] = 1'b0 ;
   assign ext_mem_adr_o[0] = 1'b0 ;
   assign ext_mem_adr_o[1] = 1'b0 ;
   assign ext_mem_adr_o[2] = 1'b0 ;
   assign ext_mem_adr_o[3] = 1'b0 ;
   assign ext_mem_adr_o[4] = 1'b0 ;
   assign ext_mem_adr_o[5] = 1'b0 ;
   assign ext_mem_adr_o[6] = 1'b0 ;
   assign ext_mem_adr_o[7] = 1'b0 ;
   assign ext_mem_adr_o[8] = 1'b0 ;
   assign ext_mem_adr_o[9] = 1'b0 ;
   assign ext_mem_adr_o[10] = 1'b0 ;
   assign ext_mem_adr_o[11] = 1'b0 ;
   assign ext_mem_adr_o[12] = 1'b0 ;
   assign ext_mem_adr_o[13] = 1'b0 ;
   assign ext_mem_adr_o[14] = 1'b0 ;
   assign ext_mem_adr_o[15] = 1'b0 ;
   assign ext_mem_adr_o[16] = 1'b0 ;
   assign ext_mem_adr_o[17] = 1'b0 ;
   assign ext_mem_adr_o[18] = 1'b0 ;
   assign ext_mem_adr_o[19] = 1'b0 ;
   assign ext_mem_adr_o[20] = 1'b0 ;
   assign ext_mem_adr_o[21] = 1'b0 ;
   assign ext_mem_adr_o[22] = 1'b0 ;
   assign ext_mem_adr_o[23] = 1'b0 ;
   assign ext_mem_adr_o[24] = 1'b0 ;
   assign ext_mem_adr_o[25] = 1'b0 ;
   assign ext_mem_adr_o[26] = 1'b0 ;
   assign ext_mem_adr_o[27] = 1'b0 ;
   assign ext_mem_adr_o[28] = 1'b0 ;
   assign ext_mem_adr_o[29] = 1'b0 ;
   assign ext_mem_adr_o[30] = 1'b0 ;
   assign ext_mem_adr_o[31] = 1'b0 ;

   sky130_osu_sc_18T_ms__buf_1 FE_OFC5_prot_sel (.Y(FE_OFN5_prot_sel),
	.A(prot_sel));
   sky130_osu_sc_18T_ms__buf_1 FE_OFC4_comm_sel (.Y(FE_OFN4_comm_sel),
	.A(comm_sel));
   sky130_osu_sc_18T_ms__buf_1 FE_OFC3_adc_sel (.Y(FE_OFN3_adc_sel),
	.A(adc_sel));
   sky130_osu_sc_18T_ms__buf_8 CTS_ccl_a_buf_00006 (.Y(CTS_4),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_4 CTS_ccl_a_buf_00005 (.Y(CTS_3),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_4 CTS_ccl_a_buf_00004 (.Y(CTS_2),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_8 CTS_ccl_a_buf_00003 (.Y(CTS_1),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_8 CTS_ccl_a_buf_00002 (.Y(CTS_7),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_8 CTS_ccl_a_buf_00001 (.Y(CTS_6),
	.A(clk));
   sky130_osu_sc_18T_ms__buf_1 FE_OFC3_n_482 (.Y(FE_OFN3_n_482),
	.A(n_482));
   sky130_osu_sc_18T_ms__buf_1 FE_OFC2_n_428 (.Y(FE_OFN2_n_428),
	.A(n_428));
   adc_subsystem_macro u_adc (.clk(CTS_4),
	.rst_n(rst_n),
	.wb_adr_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		n_412,
		n_413,
		n_414,
		n_415,
		n_416,
		n_417,
		n_418,
		n_419,
		n_420,
		n_421,
		n_422,
		n_423,
		n_424,
		n_425,
		n_426,
		n_427 }),
	.wb_dat_o(adc_wb_dat_miso),
	.wb_dat_i({ n_380,
		n_381,
		n_382,
		n_383,
		n_384,
		n_385,
		n_386,
		n_387,
		n_388,
		n_389,
		n_390,
		n_391,
		n_392,
		n_393,
		n_394,
		n_395,
		n_396,
		n_397,
		n_398,
		n_399,
		n_400,
		n_401,
		n_402,
		n_403,
		n_404,
		n_405,
		n_406,
		n_407,
		n_408,
		n_409,
		n_410,
		n_411 }),
	.wb_we_i(n_379),
	.wb_sel_i({ n_375,
		n_376,
		n_377,
		n_378 }),
	.wb_cyc_i(FE_OFN3_adc_sel),
	.wb_stb_i(FE_OFN3_adc_sel),
	.wb_ack_o(adc_wb_ack),
	.wb_err_o(adc_wb_err),
	.adc_data_in(adc_data_in),
	.adc_clk_out(adc_clk_out),
	.ch0_data(ch0_data),
	.ch1_data(ch1_data),
	.ch2_data(ch2_data),
	.ch3_data(ch3_data),
	.adc_data_valid(adc_data_valid),
	.irq(adc_irq),
	.adc_status({ UNCONNECTED30,
		UNCONNECTED29,
		UNCONNECTED28,
		UNCONNECTED27,
		UNCONNECTED26,
		UNCONNECTED25,
		UNCONNECTED24,
		UNCONNECTED23,
		UNCONNECTED22,
		UNCONNECTED21,
		UNCONNECTED20,
		UNCONNECTED19,
		UNCONNECTED18,
		UNCONNECTED17,
		UNCONNECTED16,
		UNCONNECTED15,
		UNCONNECTED14,
		UNCONNECTED13,
		UNCONNECTED12,
		UNCONNECTED11,
		UNCONNECTED10,
		UNCONNECTED9,
		UNCONNECTED8,
		UNCONNECTED7,
		UNCONNECTED6,
		UNCONNECTED5,
		UNCONNECTED4,
		UNCONNECTED3,
		UNCONNECTED2,
		UNCONNECTED1,
		UNCONNECTED0,
		UNCONNECTED }));
   communication_macro u_communication (.wb_we_i(n_163),
	.wb_stb_i(FE_OFN4_comm_sel),
	.wb_sel_i({ n_162,
		n_161,
		n_160,
		n_159 }),
	.wb_err_o(comm_wb_err),
	.wb_dat_o(comm_wb_dat_miso),
	.wb_dat_i({ n_195,
		n_194,
		n_193,
		n_192,
		n_191,
		n_190,
		n_189,
		n_188,
		n_187,
		n_186,
		n_185,
		n_184,
		n_183,
		n_182,
		n_181,
		n_180,
		n_179,
		n_178,
		n_177,
		n_176,
		n_175,
		n_174,
		n_173,
		n_172,
		n_171,
		n_170,
		n_169,
		n_168,
		n_167,
		n_166,
		n_165,
		n_164 }),
	.wb_cyc_i(FE_OFN4_comm_sel),
	.wb_adr_i({ FE_UNCONNECTEDZ_0,
		FE_UNCONNECTEDZ_1,
		FE_UNCONNECTEDZ_2,
		FE_UNCONNECTEDZ_3,
		FE_UNCONNECTEDZ_4,
		FE_UNCONNECTEDZ_5,
		FE_UNCONNECTEDZ_6,
		FE_UNCONNECTEDZ_7,
		FE_UNCONNECTEDZ_8,
		FE_UNCONNECTEDZ_9,
		FE_UNCONNECTEDZ_10,
		FE_UNCONNECTEDZ_11,
		FE_UNCONNECTEDZ_12,
		FE_UNCONNECTEDZ_13,
		FE_UNCONNECTEDZ_14,
		FE_UNCONNECTEDZ_15,
		n_211,
		n_210,
		n_209,
		n_208,
		n_207,
		n_206,
		n_205,
		n_204,
		n_203,
		n_202,
		n_201,
		n_200,
		n_199,
		n_198,
		n_197,
		n_196 }),
	.wb_ack_o(comm_wb_ack),
	.uart_tx(uart_tx),
	.uart_rx(uart_rx),
	.spi_sclk(spi_sclk),
	.spi_mosi(spi_mosi),
	.spi_miso(spi_miso),
	.spi_cs_n(spi_cs_n),
	.rst_n(rst_n),
	.irq(comm_irq),
	.gpio(gpio),
	.clk(CTS_3));
   rv32im_integrated_macro u_cpu_core (.clk(CTS_2),
	.rst_n(n_583),
	.iwb_adr_o(iwb_adr),
	.iwb_dat_i(iwb_dat_miso),
	.iwb_cyc_o(iwb_cyc),
	.iwb_stb_o(iwb_stb),
	.iwb_ack_i(iwb_ack),
	.dwb_adr_o(dwb_adr),
	.dwb_dat_o(dwb_dat_mosi),
	.dwb_dat_i({ n_551,
		n_552,
		n_553,
		n_554,
		n_555,
		n_556,
		n_557,
		n_558,
		n_559,
		n_560,
		n_561,
		n_562,
		n_563,
		n_564,
		n_565,
		n_566,
		n_567,
		n_568,
		n_569,
		n_570,
		n_571,
		n_572,
		n_573,
		n_574,
		n_575,
		n_576,
		n_577,
		n_578,
		n_579,
		n_580,
		n_581,
		n_582 }),
	.dwb_we_o(dwb_we),
	.dwb_sel_o(dwb_sel),
	.dwb_cyc_o(dwb_cyc),
	.dwb_stb_o(dwb_stb),
	.dwb_ack_i(n_550),
	.dwb_err_i(n_549),
	.interrupts({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		ext_interrupts,
		1'b0,
		emergency_stop,
		watchdog_timeout,
		prot_irq,
		adc_irq,
		pwm_irq,
		1'b0,
		comm_irq }));
   memory_macro u_memory (.clk(CTS_1),
	.rst_n(rst_n),
	.iwb_adr_i(iwb_adr),
	.iwb_dat_o(iwb_dat_miso),
	.iwb_dat_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0 }),
	.iwb_we_i(1'b0),
	.iwb_sel_i({ 1'b1,
		1'b1,
		1'b1,
		1'b1 }),
	.iwb_cyc_i(iwb_cyc),
	.iwb_stb_i(iwb_stb),
	.iwb_ack_o(iwb_ack),
	.iwb_err_o(UNCONNECTED31),
	.dwb_adr_i({ 1'b0,
		1'b0,
		1'b0,
		n_520,
		n_521,
		n_522,
		n_523,
		n_524,
		n_525,
		n_526,
		n_527,
		n_528,
		n_529,
		n_530,
		n_531,
		n_532,
		n_533,
		n_534,
		n_535,
		n_536,
		n_537,
		n_538,
		n_539,
		n_540,
		n_541,
		n_542,
		n_543,
		n_544,
		n_545,
		n_546,
		n_547,
		n_548 }),
	.dwb_dat_o(mem_wb_dat_miso),
	.dwb_dat_i({ n_488,
		n_489,
		n_490,
		n_491,
		n_492,
		n_493,
		n_494,
		n_495,
		n_496,
		n_497,
		n_498,
		n_499,
		n_500,
		n_501,
		n_502,
		n_503,
		n_504,
		n_505,
		n_506,
		n_507,
		n_508,
		n_509,
		n_510,
		n_511,
		n_512,
		n_513,
		n_514,
		n_515,
		n_516,
		n_517,
		n_518,
		n_519 }),
	.dwb_we_i(n_487),
	.dwb_sel_i({ n_483,
		n_484,
		n_485,
		n_486 }),
	.dwb_cyc_i(FE_OFN3_n_482),
	.dwb_stb_i(FE_OFN3_n_482),
	.dwb_ack_o(mem_wb_ack),
	.dwb_err_o(mem_wb_err),
	.ext_mem_adr_o({ UNCONNECTED63,
		UNCONNECTED62,
		UNCONNECTED61,
		UNCONNECTED60,
		UNCONNECTED59,
		UNCONNECTED58,
		UNCONNECTED57,
		UNCONNECTED56,
		UNCONNECTED55,
		UNCONNECTED54,
		UNCONNECTED53,
		UNCONNECTED52,
		UNCONNECTED51,
		UNCONNECTED50,
		UNCONNECTED49,
		UNCONNECTED48,
		UNCONNECTED47,
		UNCONNECTED46,
		UNCONNECTED45,
		UNCONNECTED44,
		UNCONNECTED43,
		UNCONNECTED42,
		UNCONNECTED41,
		UNCONNECTED40,
		UNCONNECTED39,
		UNCONNECTED38,
		UNCONNECTED37,
		UNCONNECTED36,
		UNCONNECTED35,
		UNCONNECTED34,
		UNCONNECTED33,
		UNCONNECTED32 }),
	.ext_mem_dat_o({ UNCONNECTED95,
		UNCONNECTED94,
		UNCONNECTED93,
		UNCONNECTED92,
		UNCONNECTED91,
		UNCONNECTED90,
		UNCONNECTED89,
		UNCONNECTED88,
		UNCONNECTED87,
		UNCONNECTED86,
		UNCONNECTED85,
		UNCONNECTED84,
		UNCONNECTED83,
		UNCONNECTED82,
		UNCONNECTED81,
		UNCONNECTED80,
		UNCONNECTED79,
		UNCONNECTED78,
		UNCONNECTED77,
		UNCONNECTED76,
		UNCONNECTED75,
		UNCONNECTED74,
		UNCONNECTED73,
		UNCONNECTED72,
		UNCONNECTED71,
		UNCONNECTED70,
		UNCONNECTED69,
		UNCONNECTED68,
		UNCONNECTED67,
		UNCONNECTED66,
		UNCONNECTED65,
		UNCONNECTED64 }),
	.ext_mem_dat_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0 }),
	.ext_mem_we_o(UNCONNECTED96),
	.ext_mem_sel_o({ UNCONNECTED100,
		UNCONNECTED99,
		UNCONNECTED98,
		UNCONNECTED97 }),
	.ext_mem_cyc_o(UNCONNECTED101),
	.ext_mem_stb_o(UNCONNECTED102),
	.ext_mem_ack_i(1'b0),
	.ext_mem_err_i(1'b0),
	.rom_ready(UNCONNECTED103),
	.ram_ready(UNCONNECTED104),
	.memory_status({ UNCONNECTED136,
		UNCONNECTED135,
		UNCONNECTED134,
		UNCONNECTED133,
		UNCONNECTED132,
		UNCONNECTED131,
		UNCONNECTED130,
		UNCONNECTED129,
		UNCONNECTED128,
		UNCONNECTED127,
		UNCONNECTED126,
		UNCONNECTED125,
		UNCONNECTED124,
		UNCONNECTED123,
		UNCONNECTED122,
		UNCONNECTED121,
		UNCONNECTED120,
		UNCONNECTED119,
		UNCONNECTED118,
		UNCONNECTED117,
		UNCONNECTED116,
		UNCONNECTED115,
		UNCONNECTED114,
		UNCONNECTED113,
		UNCONNECTED112,
		UNCONNECTED111,
		UNCONNECTED110,
		UNCONNECTED109,
		UNCONNECTED108,
		UNCONNECTED107,
		UNCONNECTED106,
		UNCONNECTED105 }));
   protection_macro u_protection (.clk(CTS_7),
	.rst_n(rst_n),
	.wb_adr_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		n_355,
		n_356,
		n_357,
		n_358,
		n_359,
		n_360,
		n_361,
		n_362,
		n_363,
		n_364,
		n_365,
		n_366,
		n_367,
		n_368,
		n_369,
		n_370 }),
	.wb_dat_o(prot_wb_dat_miso),
	.wb_dat_i({ n_323,
		n_324,
		n_325,
		n_326,
		n_327,
		n_328,
		n_329,
		n_330,
		n_331,
		n_332,
		n_333,
		n_334,
		n_335,
		n_336,
		n_337,
		n_338,
		n_339,
		n_340,
		n_341,
		n_342,
		n_343,
		n_344,
		n_345,
		n_346,
		n_347,
		n_348,
		n_349,
		n_350,
		n_351,
		n_352,
		n_353,
		n_354 }),
	.wb_we_i(n_322),
	.wb_sel_i({ n_318,
		n_319,
		n_320,
		n_321 }),
	.wb_cyc_i(FE_OFN5_prot_sel),
	.wb_stb_i(FE_OFN5_prot_sel),
	.wb_ack_o(prot_wb_ack),
	.wb_err_o(prot_wb_err),
	.current_sense(current_sense),
	.voltage_sense(voltage_sense),
	.thermal_alert_in(thermal_alert_in),
	.emergency_stop(emergency_stop),
	.channel_disable(channel_disable),
	.system_reset(system_reset),
	.watchdog_kick(1'b0),
	.watchdog_timeout(watchdog_timeout),
	.irq(prot_irq),
	.protection_status({ UNCONNECTED168,
		UNCONNECTED167,
		UNCONNECTED166,
		UNCONNECTED165,
		UNCONNECTED164,
		UNCONNECTED163,
		UNCONNECTED162,
		UNCONNECTED161,
		UNCONNECTED160,
		UNCONNECTED159,
		UNCONNECTED158,
		UNCONNECTED157,
		UNCONNECTED156,
		UNCONNECTED155,
		UNCONNECTED154,
		UNCONNECTED153,
		UNCONNECTED152,
		UNCONNECTED151,
		UNCONNECTED150,
		UNCONNECTED149,
		UNCONNECTED148,
		UNCONNECTED147,
		UNCONNECTED146,
		UNCONNECTED145,
		UNCONNECTED144,
		UNCONNECTED143,
		UNCONNECTED142,
		UNCONNECTED141,
		UNCONNECTED140,
		UNCONNECTED139,
		UNCONNECTED138,
		UNCONNECTED137 }));
   pwm_accelerator_macro u_pwm (.clk(CTS_6),
	.rst_n(rst_n),
	.wb_adr_i({ 1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		1'b0,
		n_466,
		n_467,
		n_468,
		n_469,
		n_470,
		n_471,
		n_472,
		n_473,
		n_474,
		n_475,
		n_476,
		n_477,
		n_478,
		n_479,
		n_480,
		n_481 }),
	.wb_dat_o(pwm_wb_dat_miso),
	.wb_dat_i({ n_434,
		n_435,
		n_436,
		n_437,
		n_438,
		n_439,
		n_440,
		n_441,
		n_442,
		n_443,
		n_444,
		n_445,
		n_446,
		n_447,
		n_448,
		n_449,
		n_450,
		n_451,
		n_452,
		n_453,
		n_454,
		n_455,
		n_456,
		n_457,
		n_458,
		n_459,
		n_460,
		n_461,
		n_462,
		n_463,
		n_464,
		n_465 }),
	.wb_we_i(n_433),
	.wb_sel_i({ n_429,
		n_430,
		n_431,
		n_432 }),
	.wb_cyc_i(FE_OFN2_n_428),
	.wb_stb_i(FE_OFN2_n_428),
	.wb_ack_o(pwm_wb_ack),
	.wb_err_o(pwm_wb_err),
	.pwm_out(pwm_out),
	.pwm_out_n(pwm_out_n),
	.irq(pwm_irq),
	.pwm_sync_out(UNCONNECTED169),
	.pwm_sync_in(1'b0),
	.pwm_status({ UNCONNECTED201,
		UNCONNECTED200,
		UNCONNECTED199,
		UNCONNECTED198,
		UNCONNECTED197,
		UNCONNECTED196,
		UNCONNECTED195,
		UNCONNECTED194,
		UNCONNECTED193,
		UNCONNECTED192,
		UNCONNECTED191,
		UNCONNECTED190,
		UNCONNECTED189,
		UNCONNECTED188,
		UNCONNECTED187,
		UNCONNECTED186,
		UNCONNECTED185,
		UNCONNECTED184,
		UNCONNECTED183,
		UNCONNECTED182,
		UNCONNECTED181,
		UNCONNECTED180,
		UNCONNECTED179,
		UNCONNECTED178,
		UNCONNECTED177,
		UNCONNECTED176,
		UNCONNECTED175,
		UNCONNECTED174,
		UNCONNECTED173,
		UNCONNECTED172,
		UNCONNECTED171,
		UNCONNECTED170 }));
   sky130_osu_sc_18T_ms__nand2_l g7283__2398 (.Y(n_560),
	.A(n_128),
	.B(n_76));
   sky130_osu_sc_18T_ms__nand2_l g7284__5107 (.Y(n_569),
	.A(n_130),
	.B(n_89));
   sky130_osu_sc_18T_ms__nand2_l g7285__6260 (.Y(n_564),
	.A(n_124),
	.B(n_31));
   sky130_osu_sc_18T_ms__nand2_l g7286__4319 (.Y(n_578),
	.A(n_125),
	.B(n_41));
   sky130_osu_sc_18T_ms__nand2_l g7287__8428 (.Y(n_582),
	.A(n_123),
	.B(n_26));
   sky130_osu_sc_18T_ms__nand2_l g7288__5526 (.Y(n_549),
	.A(n_131),
	.B(n_86));
   sky130_osu_sc_18T_ms__nand2_l g7289__6783 (.Y(n_570),
	.A(n_129),
	.B(n_87));
   sky130_osu_sc_18T_ms__nand2_l g7290__3680 (.Y(n_576),
	.A(n_126),
	.B(n_48));
   sky130_osu_sc_18T_ms__nand2_l g7291__1617 (.Y(n_561),
	.A(n_127),
	.B(n_51));
   sky130_osu_sc_18T_ms__nand2_l g7292__2802 (.Y(n_556),
	.A(n_132),
	.B(n_21));
   sky130_osu_sc_18T_ms__nand2_l g7293__1705 (.Y(n_566),
	.A(n_154),
	.B(n_100));
   sky130_osu_sc_18T_ms__nand2_l g7294__5122 (.Y(n_567),
	.A(n_153),
	.B(n_97));
   sky130_osu_sc_18T_ms__nand2_l g7295__8246 (.Y(n_557),
	.A(n_151),
	.B(n_96));
   sky130_osu_sc_18T_ms__nand2_l g7296__7098 (.Y(n_568),
	.A(n_152),
	.B(n_94));
   sky130_osu_sc_18T_ms__nand2_l g7297__6131 (.Y(n_558),
	.A(n_150),
	.B(n_90));
   sky130_osu_sc_18T_ms__nand2_l g7298__1881 (.Y(n_552),
	.A(n_156),
	.B(n_98));
   sky130_osu_sc_18T_ms__nand2_l g7299__5115 (.Y(n_559),
	.A(n_148),
	.B(n_82));
   sky130_osu_sc_18T_ms__nand2_l g7300__7482 (.Y(n_571),
	.A(n_149),
	.B(n_83));
   sky130_osu_sc_18T_ms__nand2_l g7301__4733 (.Y(n_572),
	.A(n_147),
	.B(n_79));
   sky130_osu_sc_18T_ms__nand2_l g7302__6161 (.Y(n_553),
	.A(n_146),
	.B(n_80));
   sky130_osu_sc_18T_ms__nand2_l g7303__9315 (.Y(n_573),
	.A(n_145),
	.B(n_75));
   sky130_osu_sc_18T_ms__nand2_l g7304__9945 (.Y(n_574),
	.A(n_144),
	.B(n_71));
   sky130_osu_sc_18T_ms__nand2_l g7305__2883 (.Y(n_575),
	.A(n_142),
	.B(n_52));
   sky130_osu_sc_18T_ms__nand2_l g7306__2346 (.Y(n_554),
	.A(n_143),
	.B(n_53));
   sky130_osu_sc_18T_ms__nand2_l g7307__1666 (.Y(n_562),
	.A(n_141),
	.B(n_45));
   sky130_osu_sc_18T_ms__nand2_l g7308__7410 (.Y(n_577),
	.A(n_140),
	.B(n_44));
   sky130_osu_sc_18T_ms__nand2_l g7309__6417 (.Y(n_555),
	.A(n_136),
	.B(n_32));
   sky130_osu_sc_18T_ms__nand2_l g7310__5477 (.Y(n_563),
	.A(n_138),
	.B(n_36));
   sky130_osu_sc_18T_ms__nand2_l g7311__2398 (.Y(n_579),
	.A(n_139),
	.B(n_38));
   sky130_osu_sc_18T_ms__nand2_l g7312__5107 (.Y(n_551),
	.A(n_134),
	.B(n_24));
   sky130_osu_sc_18T_ms__nand2_l g7313__6260 (.Y(n_580),
	.A(n_137),
	.B(n_35));
   sky130_osu_sc_18T_ms__nand2_l g7314__4319 (.Y(n_581),
	.A(n_135),
	.B(n_30));
   sky130_osu_sc_18T_ms__nand2_l g7315__8428 (.Y(n_565),
	.A(n_155),
	.B(n_23));
   sky130_osu_sc_18T_ms__nand2_l g7316__5526 (.Y(n_550),
	.A(n_133),
	.B(n_22));
   sky130_osu_sc_18T_ms__aoi21_l g7317__6783 (.Y(n_156),
	.A0(prot_wb_dat_miso[30]),
	.A1(prot_sel),
	.B0(n_114));
   sky130_osu_sc_18T_ms__aoi21_l g7318__3680 (.Y(n_155),
	.A0(prot_wb_dat_miso[17]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_120));
   sky130_osu_sc_18T_ms__aoi21_l g7319__1617 (.Y(n_154),
	.A0(prot_wb_dat_miso[16]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_118));
   sky130_osu_sc_18T_ms__aoi21_l g7320__2802 (.Y(n_153),
	.A0(prot_wb_dat_miso[15]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_117));
   sky130_osu_sc_18T_ms__aoi21_l g7321__1705 (.Y(n_152),
	.A0(prot_wb_dat_miso[14]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_115));
   sky130_osu_sc_18T_ms__aoi21_l g7322__5122 (.Y(n_151),
	.A0(prot_wb_dat_miso[25]),
	.A1(prot_sel),
	.B0(n_116));
   sky130_osu_sc_18T_ms__aoi21_l g7323__8246 (.Y(n_150),
	.A0(prot_wb_dat_miso[24]),
	.A1(prot_sel),
	.B0(n_111));
   sky130_osu_sc_18T_ms__aoi21_l g7324__7098 (.Y(n_149),
	.A0(pwm_wb_dat_miso[11]),
	.A1(FE_OFN2_n_428),
	.B0(n_110));
   sky130_osu_sc_18T_ms__aoi21_l g7325__6131 (.Y(n_148),
	.A0(pwm_wb_dat_miso[23]),
	.A1(FE_OFN2_n_428),
	.B0(n_108));
   sky130_osu_sc_18T_ms__aoi21_l g7326__1881 (.Y(n_147),
	.A0(pwm_wb_dat_miso[10]),
	.A1(FE_OFN2_n_428),
	.B0(n_109));
   sky130_osu_sc_18T_ms__aoi21_l g7327__5115 (.Y(n_146),
	.A0(pwm_wb_dat_miso[29]),
	.A1(FE_OFN2_n_428),
	.B0(n_107));
   sky130_osu_sc_18T_ms__aoi21_l g7328__7482 (.Y(n_145),
	.A0(pwm_wb_dat_miso[9]),
	.A1(FE_OFN2_n_428),
	.B0(n_106));
   sky130_osu_sc_18T_ms__aoi21_l g7329__4733 (.Y(n_144),
	.A0(pwm_wb_dat_miso[8]),
	.A1(FE_OFN2_n_428),
	.B0(n_70));
   sky130_osu_sc_18T_ms__aoi21_l g7330__6161 (.Y(n_143),
	.A0(prot_wb_dat_miso[28]),
	.A1(prot_sel),
	.B0(n_62));
   sky130_osu_sc_18T_ms__aoi21_l g7331__9315 (.Y(n_142),
	.A0(prot_wb_dat_miso[7]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_69));
   sky130_osu_sc_18T_ms__aoi21_l g7332__9945 (.Y(n_141),
	.A0(prot_wb_dat_miso[20]),
	.A1(prot_sel),
	.B0(n_64));
   sky130_osu_sc_18T_ms__aoi21_l g7333__2883 (.Y(n_140),
	.A0(prot_wb_dat_miso[5]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_65));
   sky130_osu_sc_18T_ms__aoi21_l g7334__2346 (.Y(n_139),
	.A0(prot_wb_dat_miso[3]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_61));
   sky130_osu_sc_18T_ms__aoi21_l g7335__1666 (.Y(n_138),
	.A0(pwm_wb_dat_miso[19]),
	.A1(FE_OFN2_n_428),
	.B0(n_60));
   sky130_osu_sc_18T_ms__aoi21_l g7336__7410 (.Y(n_137),
	.A0(prot_wb_dat_miso[2]),
	.A1(FE_OFN5_prot_sel),
	.B0(n_59));
   sky130_osu_sc_18T_ms__aoi21_l g7337__6417 (.Y(n_136),
	.A0(prot_wb_dat_miso[27]),
	.A1(prot_sel),
	.B0(n_58));
   sky130_osu_sc_18T_ms__aoi21_l g7338__5477 (.Y(n_135),
	.A0(pwm_wb_dat_miso[1]),
	.A1(FE_OFN2_n_428),
	.B0(n_57));
   sky130_osu_sc_18T_ms__aoi21_l g7339__2398 (.Y(n_134),
	.A0(pwm_wb_dat_miso[31]),
	.A1(FE_OFN2_n_428),
	.B0(n_122));
   sky130_osu_sc_18T_ms__aoi21_l g7340__5107 (.Y(n_133),
	.A0(prot_wb_ack),
	.A1(FE_OFN5_prot_sel),
	.B0(n_121));
   sky130_osu_sc_18T_ms__aoi21_l g7341__6260 (.Y(n_132),
	.A0(comm_wb_dat_miso[26]),
	.A1(FE_OFN4_comm_sel),
	.B0(n_119));
   sky130_osu_sc_18T_ms__aoi21_l g7342__4319 (.Y(n_131),
	.A0(comm_wb_err),
	.A1(FE_OFN4_comm_sel),
	.B0(n_68));
   sky130_osu_sc_18T_ms__aoi21_l g7343__8428 (.Y(n_130),
	.A0(adc_wb_dat_miso[13]),
	.A1(adc_sel),
	.B0(n_113));
   sky130_osu_sc_18T_ms__aoi21_l g7344__5526 (.Y(n_129),
	.A0(comm_wb_dat_miso[12]),
	.A1(FE_OFN4_comm_sel),
	.B0(n_112));
   sky130_osu_sc_18T_ms__aoi21_l g7345__6783 (.Y(n_128),
	.A0(adc_wb_dat_miso[22]),
	.A1(adc_sel),
	.B0(n_105));
   sky130_osu_sc_18T_ms__aoi21_l g7346__3680 (.Y(n_127),
	.A0(comm_wb_dat_miso[21]),
	.A1(comm_sel),
	.B0(n_67));
   sky130_osu_sc_18T_ms__aoi21_l g7347__1617 (.Y(n_126),
	.A0(comm_wb_dat_miso[6]),
	.A1(FE_OFN4_comm_sel),
	.B0(n_66));
   sky130_osu_sc_18T_ms__aoi21_l g7348__2802 (.Y(n_125),
	.A0(adc_wb_dat_miso[4]),
	.A1(adc_sel),
	.B0(n_63));
   sky130_osu_sc_18T_ms__aoi21_l g7349__1705 (.Y(n_124),
	.A0(adc_wb_dat_miso[18]),
	.A1(adc_sel),
	.B0(n_56));
   sky130_osu_sc_18T_ms__aoi21_l g7350__5122 (.Y(n_123),
	.A0(adc_wb_dat_miso[0]),
	.A1(adc_sel),
	.B0(n_55));
   sky130_osu_sc_18T_ms__inv_1 g7351 (.Y(n_122),
	.A(n_104));
   sky130_osu_sc_18T_ms__inv_1 g7352 (.Y(n_121),
	.A(n_103));
   sky130_osu_sc_18T_ms__inv_1 g7353 (.Y(n_120),
	.A(n_102));
   sky130_osu_sc_18T_ms__inv_1 g7354 (.Y(n_119),
	.A(n_101));
   sky130_osu_sc_18T_ms__inv_1 g7355 (.Y(n_118),
	.A(n_99));
   sky130_osu_sc_18T_ms__inv_1 g7356 (.Y(n_117),
	.A(n_95));
   sky130_osu_sc_18T_ms__inv_1 g7357 (.Y(n_116),
	.A(n_93));
   sky130_osu_sc_18T_ms__inv_1 g7358 (.Y(n_115),
	.A(n_92));
   sky130_osu_sc_18T_ms__inv_1 g7359 (.Y(n_114),
	.A(n_91));
   sky130_osu_sc_18T_ms__inv_1 g7360 (.Y(n_113),
	.A(n_88));
   sky130_osu_sc_18T_ms__inv_1 g7361 (.Y(n_112),
	.A(n_85));
   sky130_osu_sc_18T_ms__inv_1 g7362 (.Y(n_111),
	.A(n_84));
   sky130_osu_sc_18T_ms__inv_1 g7363 (.Y(n_110),
	.A(n_81));
   sky130_osu_sc_18T_ms__inv_1 g7364 (.Y(n_109),
	.A(n_78));
   sky130_osu_sc_18T_ms__inv_1 g7365 (.Y(n_108),
	.A(n_77));
   sky130_osu_sc_18T_ms__inv_1 g7366 (.Y(n_107),
	.A(n_74));
   sky130_osu_sc_18T_ms__inv_1 g7367 (.Y(n_106),
	.A(n_73));
   sky130_osu_sc_18T_ms__inv_1 g7368 (.Y(n_105),
	.A(n_72));
   sky130_osu_sc_18T_ms__aoi22_l g7369__8246 (.Y(n_104),
	.A0(prot_wb_dat_miso[31]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[31]));
   sky130_osu_sc_18T_ms__aoi22_l g7370__7098 (.Y(n_103),
	.A0(pwm_wb_ack),
	.A1(n_428),
	.B0(FE_OFN3_adc_sel),
	.B1(adc_wb_ack));
   sky130_osu_sc_18T_ms__aoi22_l g7371__6131 (.Y(n_102),
	.A0(adc_wb_dat_miso[17]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[17]));
   sky130_osu_sc_18T_ms__aoi22_l g7372__1881 (.Y(n_101),
	.A0(pwm_wb_dat_miso[26]),
	.A1(n_428),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[26]));
   sky130_osu_sc_18T_ms__aoi22_l g7373__5115 (.Y(n_100),
	.A0(pwm_wb_dat_miso[16]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[16]));
   sky130_osu_sc_18T_ms__aoi22_l g7374__7482 (.Y(n_99),
	.A0(adc_wb_dat_miso[16]),
	.A1(adc_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[16]));
   sky130_osu_sc_18T_ms__aoi22_l g7375__4733 (.Y(n_98),
	.A0(pwm_wb_dat_miso[30]),
	.A1(FE_OFN2_n_428),
	.B0(adc_sel),
	.B1(adc_wb_dat_miso[30]));
   sky130_osu_sc_18T_ms__aoi22_l g7376__6161 (.Y(n_97),
	.A0(pwm_wb_dat_miso[15]),
	.A1(n_428),
	.B0(FE_OFN4_comm_sel),
	.B1(comm_wb_dat_miso[15]));
   sky130_osu_sc_18T_ms__aoi22_l g7377__9315 (.Y(n_96),
	.A0(pwm_wb_dat_miso[25]),
	.A1(n_428),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[25]));
   sky130_osu_sc_18T_ms__aoi22_l g7378__9945 (.Y(n_95),
	.A0(adc_wb_dat_miso[15]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[15]));
   sky130_osu_sc_18T_ms__aoi22_l g7379__2883 (.Y(n_94),
	.A0(comm_wb_dat_miso[14]),
	.A1(FE_OFN4_comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[14]));
   sky130_osu_sc_18T_ms__aoi22_l g7380__2346 (.Y(n_93),
	.A0(adc_wb_dat_miso[25]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[25]));
   sky130_osu_sc_18T_ms__aoi22_l g7381__1666 (.Y(n_92),
	.A0(pwm_wb_dat_miso[14]),
	.A1(FE_OFN2_n_428),
	.B0(adc_sel),
	.B1(adc_wb_dat_miso[14]));
   sky130_osu_sc_18T_ms__aoi22_l g7382__7410 (.Y(n_91),
	.A0(comm_wb_dat_miso[30]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[30]));
   sky130_osu_sc_18T_ms__aoi22_l g7383__6417 (.Y(n_90),
	.A0(pwm_wb_dat_miso[24]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[24]));
   sky130_osu_sc_18T_ms__aoi22_l g7384__5477 (.Y(n_89),
	.A0(pwm_wb_dat_miso[13]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[13]));
   sky130_osu_sc_18T_ms__aoi22_l g7385__2398 (.Y(n_88),
	.A0(prot_wb_dat_miso[13]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[13]));
   sky130_osu_sc_18T_ms__aoi22_l g7386__5107 (.Y(n_87),
	.A0(pwm_wb_dat_miso[12]),
	.A1(n_428),
	.B0(FE_OFN5_prot_sel),
	.B1(prot_wb_dat_miso[12]));
   sky130_osu_sc_18T_ms__aoi22_l g7387__6260 (.Y(n_86),
	.A0(adc_wb_err),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_err));
   sky130_osu_sc_18T_ms__aoi22_l g7388__4319 (.Y(n_85),
	.A0(adc_wb_dat_miso[12]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[12]));
   sky130_osu_sc_18T_ms__aoi22_l g7389__8428 (.Y(n_84),
	.A0(adc_wb_dat_miso[24]),
	.A1(adc_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[24]));
   sky130_osu_sc_18T_ms__aoi22_l g7390__5526 (.Y(n_83),
	.A0(prot_wb_dat_miso[11]),
	.A1(prot_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[11]));
   sky130_osu_sc_18T_ms__aoi22_l g7391__6783 (.Y(n_82),
	.A0(comm_wb_dat_miso[23]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[23]));
   sky130_osu_sc_18T_ms__aoi22_l g7392__3680 (.Y(n_81),
	.A0(adc_wb_dat_miso[11]),
	.A1(adc_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[11]));
   sky130_osu_sc_18T_ms__aoi22_l g7393__1617 (.Y(n_80),
	.A0(prot_wb_dat_miso[29]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[29]));
   sky130_osu_sc_18T_ms__aoi22_l g7394__2802 (.Y(n_79),
	.A0(comm_wb_dat_miso[10]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[10]));
   sky130_osu_sc_18T_ms__aoi22_l g7395__1705 (.Y(n_78),
	.A0(adc_wb_dat_miso[10]),
	.A1(adc_sel),
	.B0(prot_sel),
	.B1(prot_wb_dat_miso[10]));
   sky130_osu_sc_18T_ms__aoi22_l g7396__5122 (.Y(n_77),
	.A0(adc_wb_dat_miso[23]),
	.A1(adc_sel),
	.B0(prot_sel),
	.B1(prot_wb_dat_miso[23]));
   sky130_osu_sc_18T_ms__aoi22_l g7397__8246 (.Y(n_76),
	.A0(prot_wb_dat_miso[22]),
	.A1(prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[22]));
   sky130_osu_sc_18T_ms__aoi22_l g7398__7098 (.Y(n_75),
	.A0(adc_wb_dat_miso[9]),
	.A1(adc_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[9]));
   sky130_osu_sc_18T_ms__aoi22_l g7399__6131 (.Y(n_74),
	.A0(adc_wb_dat_miso[29]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[29]));
   sky130_osu_sc_18T_ms__aoi22_l g7400__1881 (.Y(n_73),
	.A0(prot_wb_dat_miso[9]),
	.A1(FE_OFN5_prot_sel),
	.B0(FE_OFN4_comm_sel),
	.B1(comm_wb_dat_miso[9]));
   sky130_osu_sc_18T_ms__aoi22_l g7401__5115 (.Y(n_72),
	.A0(pwm_wb_dat_miso[22]),
	.A1(FE_OFN2_n_428),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[22]));
   sky130_osu_sc_18T_ms__aoi22_l g7402__7482 (.Y(n_71),
	.A0(prot_wb_dat_miso[8]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[8]));
   sky130_osu_sc_18T_ms__inv_1 g7403 (.Y(n_70),
	.A(n_54));
   sky130_osu_sc_18T_ms__inv_1 g7404 (.Y(n_69),
	.A(n_50));
   sky130_osu_sc_18T_ms__inv_1 g7405 (.Y(n_68),
	.A(n_49));
   sky130_osu_sc_18T_ms__inv_1 g7406 (.Y(n_67),
	.A(n_47));
   sky130_osu_sc_18T_ms__inv_1 g7407 (.Y(n_66),
	.A(n_46));
   sky130_osu_sc_18T_ms__inv_1 g7408 (.Y(n_65),
	.A(n_43));
   sky130_osu_sc_18T_ms__inv_1 g7409 (.Y(n_64),
	.A(n_42));
   sky130_osu_sc_18T_ms__inv_1 g7410 (.Y(n_63),
	.A(n_40));
   sky130_osu_sc_18T_ms__inv_1 g7411 (.Y(n_62),
	.A(n_39));
   sky130_osu_sc_18T_ms__inv_1 g7412 (.Y(n_61),
	.A(n_37));
   sky130_osu_sc_18T_ms__inv_1 g7413 (.Y(n_60),
	.A(n_34));
   sky130_osu_sc_18T_ms__inv_1 g7414 (.Y(n_59),
	.A(n_33));
   sky130_osu_sc_18T_ms__inv_1 g7415 (.Y(n_58),
	.A(n_29));
   sky130_osu_sc_18T_ms__inv_1 g7416 (.Y(n_57),
	.A(n_28));
   sky130_osu_sc_18T_ms__inv_1 g7417 (.Y(n_56),
	.A(n_27));
   sky130_osu_sc_18T_ms__inv_1 g7418 (.Y(n_55),
	.A(n_25));
   sky130_osu_sc_18T_ms__aoi22_l g7419__4733 (.Y(n_54),
	.A0(adc_wb_dat_miso[8]),
	.A1(adc_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[8]));
   sky130_osu_sc_18T_ms__aoi22_l g7420__6161 (.Y(n_53),
	.A0(pwm_wb_dat_miso[28]),
	.A1(FE_OFN2_n_428),
	.B0(adc_sel),
	.B1(adc_wb_dat_miso[28]));
   sky130_osu_sc_18T_ms__aoi22_l g7421__9315 (.Y(n_52),
	.A0(adc_wb_dat_miso[7]),
	.A1(adc_sel),
	.B0(FE_OFN4_comm_sel),
	.B1(comm_wb_dat_miso[7]));
   sky130_osu_sc_18T_ms__aoi22_l g7422__9945 (.Y(n_51),
	.A0(pwm_wb_dat_miso[21]),
	.A1(n_428),
	.B0(prot_sel),
	.B1(prot_wb_dat_miso[21]));
   sky130_osu_sc_18T_ms__aoi22_l g7423__2883 (.Y(n_50),
	.A0(pwm_wb_dat_miso[7]),
	.A1(n_428),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[7]));
   sky130_osu_sc_18T_ms__aoi22_l g7424__2346 (.Y(n_49),
	.A0(pwm_wb_err),
	.A1(n_428),
	.B0(prot_sel),
	.B1(prot_wb_err));
   sky130_osu_sc_18T_ms__aoi22_l g7425__1666 (.Y(n_48),
	.A0(pwm_wb_dat_miso[6]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[6]));
   sky130_osu_sc_18T_ms__aoi22_l g7426__7410 (.Y(n_47),
	.A0(adc_wb_dat_miso[21]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[21]));
   sky130_osu_sc_18T_ms__aoi22_l g7427__6417 (.Y(n_46),
	.A0(adc_wb_dat_miso[6]),
	.A1(adc_sel),
	.B0(FE_OFN5_prot_sel),
	.B1(prot_wb_dat_miso[6]));
   sky130_osu_sc_18T_ms__aoi22_l g7428__5477 (.Y(n_45),
	.A0(adc_wb_dat_miso[20]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[20]));
   sky130_osu_sc_18T_ms__aoi22_l g7429__2398 (.Y(n_44),
	.A0(pwm_wb_dat_miso[5]),
	.A1(n_428),
	.B0(FE_OFN4_comm_sel),
	.B1(comm_wb_dat_miso[5]));
   sky130_osu_sc_18T_ms__aoi22_l g7430__5107 (.Y(n_43),
	.A0(adc_wb_dat_miso[5]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[5]));
   sky130_osu_sc_18T_ms__aoi22_l g7431__6260 (.Y(n_42),
	.A0(pwm_wb_dat_miso[20]),
	.A1(n_428),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[20]));
   sky130_osu_sc_18T_ms__aoi22_l g7432__4319 (.Y(n_41),
	.A0(prot_wb_dat_miso[4]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[4]));
   sky130_osu_sc_18T_ms__aoi22_l g7433__8428 (.Y(n_40),
	.A0(pwm_wb_dat_miso[4]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[4]));
   sky130_osu_sc_18T_ms__aoi22_l g7434__5526 (.Y(n_39),
	.A0(comm_wb_dat_miso[28]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[28]));
   sky130_osu_sc_18T_ms__aoi22_l g7435__6783 (.Y(n_38),
	.A0(pwm_wb_dat_miso[3]),
	.A1(FE_OFN2_n_428),
	.B0(n_482),
	.B1(mem_wb_dat_miso[3]));
   sky130_osu_sc_18T_ms__aoi22_l g7436__3680 (.Y(n_37),
	.A0(adc_wb_dat_miso[3]),
	.A1(adc_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[3]));
   sky130_osu_sc_18T_ms__aoi22_l g7437__1617 (.Y(n_36),
	.A0(adc_wb_dat_miso[19]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[19]));
   sky130_osu_sc_18T_ms__aoi22_l g7438__2802 (.Y(n_35),
	.A0(comm_wb_dat_miso[2]),
	.A1(FE_OFN4_comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[2]));
   sky130_osu_sc_18T_ms__aoi22_l g7439__1705 (.Y(n_34),
	.A0(prot_wb_dat_miso[19]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[19]));
   sky130_osu_sc_18T_ms__aoi22_l g7440__5122 (.Y(n_33),
	.A0(pwm_wb_dat_miso[2]),
	.A1(n_428),
	.B0(FE_OFN3_adc_sel),
	.B1(adc_wb_dat_miso[2]));
   sky130_osu_sc_18T_ms__aoi22_l g7441__8246 (.Y(n_32),
	.A0(comm_wb_dat_miso[27]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[27]));
   sky130_osu_sc_18T_ms__aoi22_l g7442__7098 (.Y(n_31),
	.A0(pwm_wb_dat_miso[18]),
	.A1(n_428),
	.B0(prot_sel),
	.B1(prot_wb_dat_miso[18]));
   sky130_osu_sc_18T_ms__aoi22_l g7443__6131 (.Y(n_30),
	.A0(prot_wb_dat_miso[1]),
	.A1(FE_OFN5_prot_sel),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[1]));
   sky130_osu_sc_18T_ms__aoi22_l g7444__1881 (.Y(n_29),
	.A0(pwm_wb_dat_miso[27]),
	.A1(n_428),
	.B0(FE_OFN3_adc_sel),
	.B1(adc_wb_dat_miso[27]));
   sky130_osu_sc_18T_ms__aoi22_l g7445__5115 (.Y(n_28),
	.A0(adc_wb_dat_miso[1]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[1]));
   sky130_osu_sc_18T_ms__aoi22_l g7446__7482 (.Y(n_27),
	.A0(comm_wb_dat_miso[18]),
	.A1(comm_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[18]));
   sky130_osu_sc_18T_ms__aoi22_l g7447__4733 (.Y(n_26),
	.A0(pwm_wb_dat_miso[0]),
	.A1(n_428),
	.B0(comm_sel),
	.B1(comm_wb_dat_miso[0]));
   sky130_osu_sc_18T_ms__aoi22_l g7448__6161 (.Y(n_25),
	.A0(prot_wb_dat_miso[0]),
	.A1(prot_sel),
	.B0(n_482),
	.B1(mem_wb_dat_miso[0]));
   sky130_osu_sc_18T_ms__aoi22_l g7449__9315 (.Y(n_24),
	.A0(adc_wb_dat_miso[31]),
	.A1(FE_OFN3_adc_sel),
	.B0(FE_OFN3_n_482),
	.B1(mem_wb_dat_miso[31]));
   sky130_osu_sc_18T_ms__aoi22_l g7450__9945 (.Y(n_23),
	.A0(pwm_wb_dat_miso[17]),
	.A1(n_428),
	.B0(FE_OFN4_comm_sel),
	.B1(comm_wb_dat_miso[17]));
   sky130_osu_sc_18T_ms__aoi22_l g7451__2883 (.Y(n_22),
	.A0(comm_wb_ack),
	.A1(FE_OFN4_comm_sel),
	.B0(n_482),
	.B1(mem_wb_ack));
   sky130_osu_sc_18T_ms__aoi22_l g7452__2346 (.Y(n_21),
	.A0(adc_wb_dat_miso[26]),
	.A1(adc_sel),
	.B0(prot_sel),
	.B1(prot_wb_dat_miso[26]));
   sky130_osu_sc_18T_ms__and2_l g7453__1666 (.Y(n_163),
	.A(FE_OFN4_comm_sel),
	.B(dwb_we));
   sky130_osu_sc_18T_ms__and2_l g7454__7410 (.Y(n_395),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[16]));
   sky130_osu_sc_18T_ms__and2_l g7455__6417 (.Y(n_421),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[6]));
   sky130_osu_sc_18T_ms__and2_l g7456__5477 (.Y(n_423),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[4]));
   sky130_osu_sc_18T_ms__and2_l g7457__2398 (.Y(n_397),
	.A(adc_sel),
	.B(dwb_dat_mosi[14]));
   sky130_osu_sc_18T_ms__and2_l g7458__5107 (.Y(n_389),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[22]));
   sky130_osu_sc_18T_ms__and2_l g7459__6260 (.Y(n_419),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[8]));
   sky130_osu_sc_18T_ms__and2_l g7460__4319 (.Y(n_393),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[18]));
   sky130_osu_sc_18T_ms__and2_l g7461__8428 (.Y(n_417),
	.A(adc_sel),
	.B(dwb_adr[10]));
   sky130_osu_sc_18T_ms__and2_l g7462__5526 (.Y(n_377),
	.A(FE_OFN3_adc_sel),
	.B(dwb_sel[1]));
   sky130_osu_sc_18T_ms__and2_l g7463__6783 (.Y(n_425),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[2]));
   sky130_osu_sc_18T_ms__and2_l g7464__3680 (.Y(n_375),
	.A(FE_OFN3_adc_sel),
	.B(dwb_sel[3]));
   sky130_osu_sc_18T_ms__and2_l g7465__1617 (.Y(n_376),
	.A(adc_sel),
	.B(dwb_sel[2]));
   sky130_osu_sc_18T_ms__and2_l g7466__2802 (.Y(n_378),
	.A(FE_OFN3_adc_sel),
	.B(dwb_sel[0]));
   sky130_osu_sc_18T_ms__and2_l g7467__1705 (.Y(n_379),
	.A(FE_OFN3_adc_sel),
	.B(dwb_we));
   sky130_osu_sc_18T_ms__and2_l g7468__5122 (.Y(n_380),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[31]));
   sky130_osu_sc_18T_ms__and2_l g7469__8246 (.Y(n_382),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[29]));
   sky130_osu_sc_18T_ms__and2_l g7470__7098 (.Y(n_383),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[28]));
   sky130_osu_sc_18T_ms__and2_l g7471__6131 (.Y(n_384),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[27]));
   sky130_osu_sc_18T_ms__and2_l g7472__1881 (.Y(n_386),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[25]));
   sky130_osu_sc_18T_ms__and2_l g7473__5115 (.Y(n_387),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[24]));
   sky130_osu_sc_18T_ms__and2_l g7474__7482 (.Y(n_388),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[23]));
   sky130_osu_sc_18T_ms__and2_l g7475__4733 (.Y(n_390),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[21]));
   sky130_osu_sc_18T_ms__and2_l g7476__6161 (.Y(n_391),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[20]));
   sky130_osu_sc_18T_ms__and2_l g7477__9315 (.Y(n_392),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[19]));
   sky130_osu_sc_18T_ms__and2_l g7478__9945 (.Y(n_385),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[26]));
   sky130_osu_sc_18T_ms__and2_l g7479__2883 (.Y(n_394),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[17]));
   sky130_osu_sc_18T_ms__and2_l g7480__2346 (.Y(n_396),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[15]));
   sky130_osu_sc_18T_ms__and2_l g7481__1666 (.Y(n_401),
	.A(adc_sel),
	.B(dwb_dat_mosi[10]));
   sky130_osu_sc_18T_ms__and2_l g7482__7410 (.Y(n_398),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[13]));
   sky130_osu_sc_18T_ms__and2_l g7483__6417 (.Y(n_399),
	.A(adc_sel),
	.B(dwb_dat_mosi[12]));
   sky130_osu_sc_18T_ms__and2_l g7484__5477 (.Y(n_400),
	.A(adc_sel),
	.B(dwb_dat_mosi[11]));
   sky130_osu_sc_18T_ms__and2_l g7485__2398 (.Y(n_402),
	.A(adc_sel),
	.B(dwb_dat_mosi[9]));
   sky130_osu_sc_18T_ms__and2_l g7486__5107 (.Y(n_403),
	.A(adc_sel),
	.B(dwb_dat_mosi[8]));
   sky130_osu_sc_18T_ms__and2_l g7487__6260 (.Y(n_404),
	.A(adc_sel),
	.B(dwb_dat_mosi[7]));
   sky130_osu_sc_18T_ms__and2_l g7488__4319 (.Y(n_406),
	.A(adc_sel),
	.B(dwb_dat_mosi[5]));
   sky130_osu_sc_18T_ms__and2_l g7489__8428 (.Y(n_407),
	.A(adc_sel),
	.B(dwb_dat_mosi[4]));
   sky130_osu_sc_18T_ms__and2_l g7490__5526 (.Y(n_408),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[3]));
   sky130_osu_sc_18T_ms__and2_l g7491__6783 (.Y(n_410),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[1]));
   sky130_osu_sc_18T_ms__and2_l g7492__3680 (.Y(n_412),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[15]));
   sky130_osu_sc_18T_ms__and2_l g7493__1617 (.Y(n_414),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[13]));
   sky130_osu_sc_18T_ms__and2_l g7494__2802 (.Y(n_415),
	.A(adc_sel),
	.B(dwb_adr[12]));
   sky130_osu_sc_18T_ms__and2_l g7495__1705 (.Y(n_416),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[11]));
   sky130_osu_sc_18T_ms__and2_l g7496__5122 (.Y(n_418),
	.A(adc_sel),
	.B(dwb_adr[9]));
   sky130_osu_sc_18T_ms__and2_l g7497__8246 (.Y(n_420),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[7]));
   sky130_osu_sc_18T_ms__and2_l g7498__7098 (.Y(n_422),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[5]));
   sky130_osu_sc_18T_ms__and2_l g7499__6131 (.Y(n_424),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[3]));
   sky130_osu_sc_18T_ms__and2_l g7500__1881 (.Y(n_426),
	.A(FE_OFN3_adc_sel),
	.B(dwb_adr[1]));
   sky130_osu_sc_18T_ms__and2_l g7501__5115 (.Y(n_427),
	.A(adc_sel),
	.B(dwb_adr[0]));
   sky130_osu_sc_18T_ms__and2_l g7502__7482 (.Y(n_409),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[2]));
   sky130_osu_sc_18T_ms__and2_l g7503__4733 (.Y(n_411),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[0]));
   sky130_osu_sc_18T_ms__and2_l g7504__6161 (.Y(n_405),
	.A(adc_sel),
	.B(dwb_dat_mosi[6]));
   sky130_osu_sc_18T_ms__and2_l g7505__9315 (.Y(n_381),
	.A(FE_OFN3_adc_sel),
	.B(dwb_dat_mosi[30]));
   sky130_osu_sc_18T_ms__and2_l g7506__9945 (.Y(n_413),
	.A(adc_sel),
	.B(dwb_adr[14]));
   sky130_osu_sc_18T_ms__and2_l g7507__2883 (.Y(n_176),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[12]));
   sky130_osu_sc_18T_ms__and2_l g7508__2346 (.Y(n_172),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[8]));
   sky130_osu_sc_18T_ms__and2_l g7509__1666 (.Y(n_178),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[14]));
   sky130_osu_sc_18T_ms__and2_l g7510__7410 (.Y(n_180),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[16]));
   sky130_osu_sc_18T_ms__and2_l g7511__6417 (.Y(n_184),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[20]));
   sky130_osu_sc_18T_ms__and2_l g7512__5477 (.Y(n_162),
	.A(FE_OFN4_comm_sel),
	.B(dwb_sel[3]));
   sky130_osu_sc_18T_ms__and2_l g7513__2398 (.Y(n_161),
	.A(FE_OFN4_comm_sel),
	.B(dwb_sel[2]));
   sky130_osu_sc_18T_ms__and2_l g7514__5107 (.Y(n_160),
	.A(FE_OFN4_comm_sel),
	.B(dwb_sel[1]));
   sky130_osu_sc_18T_ms__and2_l g7515__6260 (.Y(n_159),
	.A(FE_OFN4_comm_sel),
	.B(dwb_sel[0]));
   sky130_osu_sc_18T_ms__and2_l g7516__4319 (.Y(n_195),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[31]));
   sky130_osu_sc_18T_ms__and2_l g7517__8428 (.Y(n_194),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[30]));
   sky130_osu_sc_18T_ms__and2_l g7518__5526 (.Y(n_193),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[29]));
   sky130_osu_sc_18T_ms__and2_l g7519__6783 (.Y(n_191),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[27]));
   sky130_osu_sc_18T_ms__and2_l g7520__3680 (.Y(n_190),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[26]));
   sky130_osu_sc_18T_ms__and2_l g7521__1617 (.Y(n_189),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[25]));
   sky130_osu_sc_18T_ms__and2_l g7522__2802 (.Y(n_187),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[23]));
   sky130_osu_sc_18T_ms__and2_l g7523__1705 (.Y(n_186),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[22]));
   sky130_osu_sc_18T_ms__and2_l g7524__5122 (.Y(n_185),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[21]));
   sky130_osu_sc_18T_ms__and2_l g7525__8246 (.Y(n_188),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[24]));
   sky130_osu_sc_18T_ms__and2_l g7526__7098 (.Y(n_183),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[19]));
   sky130_osu_sc_18T_ms__and2_l g7527__6131 (.Y(n_182),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[18]));
   sky130_osu_sc_18T_ms__and2_l g7528__1881 (.Y(n_181),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[17]));
   sky130_osu_sc_18T_ms__and2_l g7529__5115 (.Y(n_179),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[15]));
   sky130_osu_sc_18T_ms__and2_l g7530__7482 (.Y(n_177),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[13]));
   sky130_osu_sc_18T_ms__and2_l g7531__4733 (.Y(n_175),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[11]));
   sky130_osu_sc_18T_ms__and2_l g7532__6161 (.Y(n_174),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[10]));
   sky130_osu_sc_18T_ms__and2_l g7533__9315 (.Y(n_173),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[9]));
   sky130_osu_sc_18T_ms__and2_l g7534__9945 (.Y(n_171),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[7]));
   sky130_osu_sc_18T_ms__and2_l g7535__2883 (.Y(n_169),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[5]));
   sky130_osu_sc_18T_ms__and2_l g7536__2346 (.Y(n_167),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[3]));
   sky130_osu_sc_18T_ms__and2_l g7537__1666 (.Y(n_166),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[2]));
   sky130_osu_sc_18T_ms__and2_l g7538__7410 (.Y(n_165),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[1]));
   sky130_osu_sc_18T_ms__and2_l g7539__6417 (.Y(n_211),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[15]));
   sky130_osu_sc_18T_ms__and2_l g7540__5477 (.Y(n_210),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[14]));
   sky130_osu_sc_18T_ms__and2_l g7541__2398 (.Y(n_209),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[13]));
   sky130_osu_sc_18T_ms__and2_l g7542__5107 (.Y(n_207),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[11]));
   sky130_osu_sc_18T_ms__and2_l g7543__6260 (.Y(n_206),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[10]));
   sky130_osu_sc_18T_ms__and2_l g7544__4319 (.Y(n_205),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[9]));
   sky130_osu_sc_18T_ms__and2_l g7545__8428 (.Y(n_203),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[7]));
   sky130_osu_sc_18T_ms__and2_l g7546__5526 (.Y(n_202),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[6]));
   sky130_osu_sc_18T_ms__and2_l g7547__6783 (.Y(n_199),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[3]));
   sky130_osu_sc_18T_ms__and2_l g7548__3680 (.Y(n_198),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[2]));
   sky130_osu_sc_18T_ms__and2_l g7549__1617 (.Y(n_197),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[1]));
   sky130_osu_sc_18T_ms__and2_l g7550__2802 (.Y(n_192),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[28]));
   sky130_osu_sc_18T_ms__and2_l g7551__1705 (.Y(n_170),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[6]));
   sky130_osu_sc_18T_ms__and2_l g7552__5122 (.Y(n_196),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[0]));
   sky130_osu_sc_18T_ms__and2_l g7553__8246 (.Y(n_201),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[5]));
   sky130_osu_sc_18T_ms__and2_l g7554__7098 (.Y(n_200),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[4]));
   sky130_osu_sc_18T_ms__and2_l g7555__6131 (.Y(n_204),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[8]));
   sky130_osu_sc_18T_ms__and2_l g7556__1881 (.Y(n_168),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[4]));
   sky130_osu_sc_18T_ms__and2_l g7557__5115 (.Y(n_208),
	.A(FE_OFN4_comm_sel),
	.B(dwb_adr[12]));
   sky130_osu_sc_18T_ms__and2_l g7558__7482 (.Y(n_164),
	.A(FE_OFN4_comm_sel),
	.B(dwb_dat_mosi[0]));
   sky130_osu_sc_18T_ms__and2_l g7559__4733 (.Y(n_328),
	.A(prot_sel),
	.B(dwb_dat_mosi[26]));
   sky130_osu_sc_18T_ms__and2_l g7560__6161 (.Y(n_370),
	.A(prot_sel),
	.B(dwb_adr[0]));
   sky130_osu_sc_18T_ms__and2_l g7561__9315 (.Y(n_329),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[25]));
   sky130_osu_sc_18T_ms__and2_l g7562__9945 (.Y(n_368),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[2]));
   sky130_osu_sc_18T_ms__and2_l g7563__2883 (.Y(n_357),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[13]));
   sky130_osu_sc_18T_ms__and2_l g7564__2346 (.Y(n_359),
	.A(prot_sel),
	.B(dwb_adr[11]));
   sky130_osu_sc_18T_ms__and2_l g7565__1666 (.Y(n_353),
	.A(prot_sel),
	.B(dwb_dat_mosi[1]));
   sky130_osu_sc_18T_ms__and2_l g7566__7410 (.Y(n_355),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[15]));
   sky130_osu_sc_18T_ms__and2_l g7567__6417 (.Y(n_349),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[5]));
   sky130_osu_sc_18T_ms__and2_l g7568__5477 (.Y(n_351),
	.A(prot_sel),
	.B(dwb_dat_mosi[3]));
   sky130_osu_sc_18T_ms__and2_l g7569__2398 (.Y(n_434),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[31]));
   sky130_osu_sc_18T_ms__and2_l g7570__5107 (.Y(n_345),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[9]));
   sky130_osu_sc_18T_ms__and2_l g7571__6260 (.Y(n_435),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[30]));
   sky130_osu_sc_18T_ms__and2_l g7572__4319 (.Y(n_436),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[29]));
   sky130_osu_sc_18T_ms__and2_l g7573__8428 (.Y(n_437),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[28]));
   sky130_osu_sc_18T_ms__and2_l g7574__5526 (.Y(n_439),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[26]));
   sky130_osu_sc_18T_ms__and2_l g7575__6783 (.Y(n_440),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[25]));
   sky130_osu_sc_18T_ms__and2_l g7576__3680 (.Y(n_443),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[22]));
   sky130_osu_sc_18T_ms__and2_l g7577__1617 (.Y(n_444),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[21]));
   sky130_osu_sc_18T_ms__and2_l g7578__2802 (.Y(n_445),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[20]));
   sky130_osu_sc_18T_ms__and2_l g7579__1705 (.Y(n_447),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[18]));
   sky130_osu_sc_18T_ms__and2_l g7580__5122 (.Y(n_448),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[17]));
   sky130_osu_sc_18T_ms__and2_l g7581__8246 (.Y(n_451),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[14]));
   sky130_osu_sc_18T_ms__and2_l g7582__7098 (.Y(n_452),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[13]));
   sky130_osu_sc_18T_ms__and2_l g7583__6131 (.Y(n_453),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[12]));
   sky130_osu_sc_18T_ms__and2_l g7584__1881 (.Y(n_430),
	.A(FE_OFN2_n_428),
	.B(dwb_sel[2]));
   sky130_osu_sc_18T_ms__and2_l g7585__5115 (.Y(n_455),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[10]));
   sky130_osu_sc_18T_ms__and2_l g7586__7482 (.Y(n_457),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[8]));
   sky130_osu_sc_18T_ms__and2_l g7587__4733 (.Y(n_339),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[15]));
   sky130_osu_sc_18T_ms__and2_l g7588__6161 (.Y(n_369),
	.A(prot_sel),
	.B(dwb_adr[1]));
   sky130_osu_sc_18T_ms__and2_l g7589__9315 (.Y(n_459),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[6]));
   sky130_osu_sc_18T_ms__and2_l g7590__9945 (.Y(n_461),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[4]));
   sky130_osu_sc_18T_ms__and2_l g7591__2883 (.Y(n_463),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[2]));
   sky130_osu_sc_18T_ms__and2_l g7592__2346 (.Y(n_464),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[1]));
   sky130_osu_sc_18T_ms__and2_l g7593__1666 (.Y(n_465),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[0]));
   sky130_osu_sc_18T_ms__and2_l g7594__7410 (.Y(n_467),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[14]));
   sky130_osu_sc_18T_ms__and2_l g7595__6417 (.Y(n_468),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[13]));
   sky130_osu_sc_18T_ms__and2_l g7596__5477 (.Y(n_469),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[12]));
   sky130_osu_sc_18T_ms__and2_l g7597__2398 (.Y(n_471),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[10]));
   sky130_osu_sc_18T_ms__and2_l g7598__5107 (.Y(n_473),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[8]));
   sky130_osu_sc_18T_ms__and2_l g7599__6260 (.Y(n_475),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[6]));
   sky130_osu_sc_18T_ms__and2_l g7600__4319 (.Y(n_476),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[5]));
   sky130_osu_sc_18T_ms__and2_l g7601__8428 (.Y(n_477),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[4]));
   sky130_osu_sc_18T_ms__and2_l g7602__5526 (.Y(n_479),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[2]));
   sky130_osu_sc_18T_ms__and2_l g7603__6783 (.Y(n_480),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[1]));
   sky130_osu_sc_18T_ms__and2_l g7604__3680 (.Y(n_341),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[13]));
   sky130_osu_sc_18T_ms__and2_l g7605__1617 (.Y(n_337),
	.A(prot_sel),
	.B(dwb_dat_mosi[17]));
   sky130_osu_sc_18T_ms__and2_l g7606__2802 (.Y(n_335),
	.A(prot_sel),
	.B(dwb_dat_mosi[19]));
   sky130_osu_sc_18T_ms__and2_l g7607__1705 (.Y(n_318),
	.A(prot_sel),
	.B(dwb_sel[3]));
   sky130_osu_sc_18T_ms__and2_l g7608__5122 (.Y(n_320),
	.A(prot_sel),
	.B(dwb_sel[1]));
   sky130_osu_sc_18T_ms__and2_l g7609__8246 (.Y(n_322),
	.A(FE_OFN5_prot_sel),
	.B(dwb_we));
   sky130_osu_sc_18T_ms__and2_l g7610__7098 (.Y(n_323),
	.A(prot_sel),
	.B(dwb_dat_mosi[31]));
   sky130_osu_sc_18T_ms__and2_l g7611__6131 (.Y(n_326),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[28]));
   sky130_osu_sc_18T_ms__and2_l g7612__1881 (.Y(n_361),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[9]));
   sky130_osu_sc_18T_ms__and2_l g7613__5115 (.Y(n_330),
	.A(prot_sel),
	.B(dwb_dat_mosi[24]));
   sky130_osu_sc_18T_ms__and2_l g7614__7482 (.Y(n_331),
	.A(prot_sel),
	.B(dwb_dat_mosi[23]));
   sky130_osu_sc_18T_ms__and2_l g7615__4733 (.Y(n_332),
	.A(prot_sel),
	.B(dwb_dat_mosi[22]));
   sky130_osu_sc_18T_ms__and2_l g7616__6161 (.Y(n_333),
	.A(prot_sel),
	.B(dwb_dat_mosi[21]));
   sky130_osu_sc_18T_ms__and2_l g7617__9315 (.Y(n_334),
	.A(prot_sel),
	.B(dwb_dat_mosi[20]));
   sky130_osu_sc_18T_ms__and2_l g7618__9945 (.Y(n_336),
	.A(prot_sel),
	.B(dwb_dat_mosi[18]));
   sky130_osu_sc_18T_ms__and2_l g7619__2883 (.Y(n_338),
	.A(prot_sel),
	.B(dwb_dat_mosi[16]));
   sky130_osu_sc_18T_ms__and2_l g7620__2346 (.Y(n_340),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[14]));
   sky130_osu_sc_18T_ms__and2_l g7621__1666 (.Y(n_342),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[12]));
   sky130_osu_sc_18T_ms__and2_l g7622__7410 (.Y(n_343),
	.A(prot_sel),
	.B(dwb_dat_mosi[11]));
   sky130_osu_sc_18T_ms__and2_l g7623__6417 (.Y(n_344),
	.A(prot_sel),
	.B(dwb_dat_mosi[10]));
   sky130_osu_sc_18T_ms__and2_l g7624__5477 (.Y(n_346),
	.A(prot_sel),
	.B(dwb_dat_mosi[8]));
   sky130_osu_sc_18T_ms__and2_l g7625__2398 (.Y(n_347),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[7]));
   sky130_osu_sc_18T_ms__and2_l g7626__5107 (.Y(n_348),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[6]));
   sky130_osu_sc_18T_ms__and2_l g7627__6260 (.Y(n_350),
	.A(prot_sel),
	.B(dwb_dat_mosi[4]));
   sky130_osu_sc_18T_ms__and2_l g7628__4319 (.Y(n_352),
	.A(prot_sel),
	.B(dwb_dat_mosi[2]));
   sky130_osu_sc_18T_ms__and2_l g7629__8428 (.Y(n_354),
	.A(prot_sel),
	.B(dwb_dat_mosi[0]));
   sky130_osu_sc_18T_ms__and2_l g7630__5526 (.Y(n_356),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[14]));
   sky130_osu_sc_18T_ms__and2_l g7631__6783 (.Y(n_358),
	.A(prot_sel),
	.B(dwb_adr[12]));
   sky130_osu_sc_18T_ms__and2_l g7632__3680 (.Y(n_360),
	.A(prot_sel),
	.B(dwb_adr[10]));
   sky130_osu_sc_18T_ms__and2_l g7633__1617 (.Y(n_362),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[8]));
   sky130_osu_sc_18T_ms__and2_l g7634__2802 (.Y(n_363),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[7]));
   sky130_osu_sc_18T_ms__and2_l g7635__1705 (.Y(n_366),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[4]));
   sky130_osu_sc_18T_ms__and2_l g7636__5122 (.Y(n_481),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[0]));
   sky130_osu_sc_18T_ms__and2_l g7637__8246 (.Y(n_454),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[11]));
   sky130_osu_sc_18T_ms__and2_l g7638__7098 (.Y(n_478),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[3]));
   sky130_osu_sc_18T_ms__and2_l g7639__6131 (.Y(n_433),
	.A(FE_OFN2_n_428),
	.B(dwb_we));
   sky130_osu_sc_18T_ms__and2_l g7640__1881 (.Y(n_431),
	.A(FE_OFN2_n_428),
	.B(dwb_sel[1]));
   sky130_osu_sc_18T_ms__and2_l g7641__5115 (.Y(n_429),
	.A(FE_OFN2_n_428),
	.B(dwb_sel[3]));
   sky130_osu_sc_18T_ms__and2_l g7642__7482 (.Y(n_327),
	.A(prot_sel),
	.B(dwb_dat_mosi[27]));
   sky130_osu_sc_18T_ms__and2_l g7643__4733 (.Y(n_474),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[7]));
   sky130_osu_sc_18T_ms__and2_l g7644__6161 (.Y(n_470),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[11]));
   sky130_osu_sc_18T_ms__and2_l g7645__9315 (.Y(n_472),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[9]));
   sky130_osu_sc_18T_ms__and2_l g7646__9945 (.Y(n_462),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[3]));
   sky130_osu_sc_18T_ms__and2_l g7647__2883 (.Y(n_466),
	.A(FE_OFN2_n_428),
	.B(dwb_adr[15]));
   sky130_osu_sc_18T_ms__and2_l g7648__2346 (.Y(n_324),
	.A(prot_sel),
	.B(dwb_dat_mosi[30]));
   sky130_osu_sc_18T_ms__and2_l g7649__1666 (.Y(n_456),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[9]));
   sky130_osu_sc_18T_ms__and2_l g7650__7410 (.Y(n_460),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[5]));
   sky130_osu_sc_18T_ms__and2_l g7651__6417 (.Y(n_325),
	.A(FE_OFN5_prot_sel),
	.B(dwb_dat_mosi[29]));
   sky130_osu_sc_18T_ms__and2_l g7652__5477 (.Y(n_458),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[7]));
   sky130_osu_sc_18T_ms__and2_l g7653__2398 (.Y(n_441),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[24]));
   sky130_osu_sc_18T_ms__and2_l g7654__5107 (.Y(n_450),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[15]));
   sky130_osu_sc_18T_ms__and2_l g7655__6260 (.Y(n_367),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[3]));
   sky130_osu_sc_18T_ms__and2_l g7656__4319 (.Y(n_449),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[16]));
   sky130_osu_sc_18T_ms__and2_l g7657__8428 (.Y(n_446),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[19]));
   sky130_osu_sc_18T_ms__and2_l g7658__5526 (.Y(n_442),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[23]));
   sky130_osu_sc_18T_ms__and2_l g7659__6783 (.Y(n_321),
	.A(FE_OFN5_prot_sel),
	.B(dwb_sel[0]));
   sky130_osu_sc_18T_ms__and2_l g7660__3680 (.Y(n_319),
	.A(prot_sel),
	.B(dwb_sel[2]));
   sky130_osu_sc_18T_ms__and2_l g7661__1617 (.Y(n_438),
	.A(FE_OFN2_n_428),
	.B(dwb_dat_mosi[27]));
   sky130_osu_sc_18T_ms__and2_l g7662__2802 (.Y(n_364),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[6]));
   sky130_osu_sc_18T_ms__and2_l g7663__1705 (.Y(n_365),
	.A(FE_OFN5_prot_sel),
	.B(dwb_adr[5]));
   sky130_osu_sc_18T_ms__and2_l g7664__5122 (.Y(n_432),
	.A(FE_OFN2_n_428),
	.B(dwb_sel[0]));
   sky130_osu_sc_18T_ms__nor2_1 g7665__8246 (.Y(comm_sel),
	.A(n_0),
	.B(n_19));
   sky130_osu_sc_18T_ms__nor2_l g7666__7098 (.Y(n_428),
	.A(dwb_adr[16]),
	.B(n_20));
   sky130_osu_sc_18T_ms__nor2_1 g7667__6131 (.Y(adc_sel),
	.A(n_0),
	.B(n_20));
   sky130_osu_sc_18T_ms__nor2_1 g7668__1881 (.Y(prot_sel),
	.A(dwb_adr[16]),
	.B(n_19));
   sky130_osu_sc_18T_ms__or2_l g7669__5115 (.Y(n_20),
	.A(dwb_adr[17]),
	.B(n_18));
   sky130_osu_sc_18T_ms__nand2_l g7670__7482 (.Y(n_19),
	.A(n_17),
	.B(dwb_adr[17]));
   sky130_osu_sc_18T_ms__inv_l g7671 (.Y(n_18),
	.A(n_17));
   sky130_osu_sc_18T_ms__nor2_l g7672__4733 (.Y(n_17),
	.A(dwb_adr[18]),
	.B(n_16));
   sky130_osu_sc_18T_ms__or2_l g7673__6161 (.Y(n_16),
	.A(dwb_adr[19]),
	.B(n_15));
   sky130_osu_sc_18T_ms__or2_l g7674__9315 (.Y(n_15),
	.A(dwb_adr[22]),
	.B(n_14));
   sky130_osu_sc_18T_ms__or2_l g7675__9945 (.Y(n_14),
	.A(dwb_adr[23]),
	.B(n_13));
   sky130_osu_sc_18T_ms__or2_l g7676__2883 (.Y(n_13),
	.A(dwb_adr[27]),
	.B(n_12));
   sky130_osu_sc_18T_ms__nand2_l g7677__2346 (.Y(n_12),
	.A(n_11),
	.B(dwb_adr[30]));
   sky130_osu_sc_18T_ms__nor2_l g7678__1666 (.Y(n_11),
	.A(dwb_adr[21]),
	.B(n_10));
   sky130_osu_sc_18T_ms__or2_l g7679__7410 (.Y(n_10),
	.A(dwb_adr[20]),
	.B(n_9));
   sky130_osu_sc_18T_ms__or2_l g7680__6417 (.Y(n_9),
	.A(dwb_adr[24]),
	.B(n_8));
   sky130_osu_sc_18T_ms__or2_l g7681__5477 (.Y(n_8),
	.A(dwb_adr[25]),
	.B(n_7));
   sky130_osu_sc_18T_ms__and2_l g7682__2398 (.Y(n_534),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[14]));
   sky130_osu_sc_18T_ms__and2_l g7683__5107 (.Y(n_520),
	.A(n_482),
	.B(dwb_adr[28]));
   sky130_osu_sc_18T_ms__and2_l g7684__6260 (.Y(n_521),
	.A(n_482),
	.B(dwb_adr[27]));
   sky130_osu_sc_18T_ms__and2_l g7685__4319 (.Y(n_522),
	.A(n_482),
	.B(dwb_adr[26]));
   sky130_osu_sc_18T_ms__and2_l g7686__8428 (.Y(n_524),
	.A(n_482),
	.B(dwb_adr[24]));
   sky130_osu_sc_18T_ms__and2_l g7687__5526 (.Y(n_525),
	.A(n_482),
	.B(dwb_adr[23]));
   sky130_osu_sc_18T_ms__and2_l g7688__6783 (.Y(n_526),
	.A(n_482),
	.B(dwb_adr[22]));
   sky130_osu_sc_18T_ms__and2_l g7689__3680 (.Y(n_528),
	.A(n_482),
	.B(dwb_adr[20]));
   sky130_osu_sc_18T_ms__and2_l g7690__1617 (.Y(n_529),
	.A(n_482),
	.B(dwb_adr[19]));
   sky130_osu_sc_18T_ms__and2_l g7691__2802 (.Y(n_530),
	.A(n_482),
	.B(dwb_adr[18]));
   sky130_osu_sc_18T_ms__and2_l g7692__1705 (.Y(n_531),
	.A(n_482),
	.B(dwb_adr[17]));
   sky130_osu_sc_18T_ms__nor2_l g7693__5122 (.Y(n_532),
	.A(n_0),
	.B(n_5));
   sky130_osu_sc_18T_ms__and2_l g7694__8246 (.Y(n_533),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[15]));
   sky130_osu_sc_18T_ms__and2_l g7695__7098 (.Y(n_535),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[13]));
   sky130_osu_sc_18T_ms__and2_l g7696__6131 (.Y(n_536),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[12]));
   sky130_osu_sc_18T_ms__and2_l g7697__1881 (.Y(n_537),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[11]));
   sky130_osu_sc_18T_ms__or2_l g7698__5115 (.Y(n_7),
	.A(dwb_adr[26]),
	.B(n_6));
   sky130_osu_sc_18T_ms__and2_l g7699__7482 (.Y(n_539),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[9]));
   sky130_osu_sc_18T_ms__and2_l g7700__4733 (.Y(n_540),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[8]));
   sky130_osu_sc_18T_ms__and2_l g7701__6161 (.Y(n_541),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[7]));
   sky130_osu_sc_18T_ms__and2_l g7702__9315 (.Y(n_542),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[6]));
   sky130_osu_sc_18T_ms__and2_l g7703__9945 (.Y(n_543),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[5]));
   sky130_osu_sc_18T_ms__and2_l g7704__2883 (.Y(n_544),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[4]));
   sky130_osu_sc_18T_ms__and2_l g7705__2346 (.Y(n_545),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[3]));
   sky130_osu_sc_18T_ms__and2_l g7706__1666 (.Y(n_546),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[2]));
   sky130_osu_sc_18T_ms__and2_l g7707__7410 (.Y(n_547),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[1]));
   sky130_osu_sc_18T_ms__and2_l g7708__6417 (.Y(n_548),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[0]));
   sky130_osu_sc_18T_ms__and2_l g7709__5477 (.Y(n_483),
	.A(FE_OFN3_n_482),
	.B(dwb_sel[3]));
   sky130_osu_sc_18T_ms__and2_l g7710__2398 (.Y(n_484),
	.A(FE_OFN3_n_482),
	.B(dwb_sel[2]));
   sky130_osu_sc_18T_ms__and2_l g7711__5107 (.Y(n_485),
	.A(FE_OFN3_n_482),
	.B(dwb_sel[1]));
   sky130_osu_sc_18T_ms__and2_l g7712__6260 (.Y(n_486),
	.A(FE_OFN3_n_482),
	.B(dwb_sel[0]));
   sky130_osu_sc_18T_ms__and2_l g7713__4319 (.Y(n_488),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[31]));
   sky130_osu_sc_18T_ms__and2_l g7714__8428 (.Y(n_489),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[30]));
   sky130_osu_sc_18T_ms__and2_l g7715__5526 (.Y(n_516),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[3]));
   sky130_osu_sc_18T_ms__and2_l g7716__6783 (.Y(n_491),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[28]));
   sky130_osu_sc_18T_ms__and2_l g7717__3680 (.Y(n_492),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[27]));
   sky130_osu_sc_18T_ms__and2_l g7718__1617 (.Y(n_511),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[8]));
   sky130_osu_sc_18T_ms__and2_l g7719__2802 (.Y(n_510),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[9]));
   sky130_osu_sc_18T_ms__and2_l g7720__1705 (.Y(n_493),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[26]));
   sky130_osu_sc_18T_ms__and2_l g7721__5122 (.Y(n_494),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[25]));
   sky130_osu_sc_18T_ms__and2_l g7722__8246 (.Y(n_495),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[24]));
   sky130_osu_sc_18T_ms__and2_l g7723__7098 (.Y(n_504),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[15]));
   sky130_osu_sc_18T_ms__and2_l g7724__6131 (.Y(n_503),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[16]));
   sky130_osu_sc_18T_ms__and2_l g7725__1881 (.Y(n_502),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[17]));
   sky130_osu_sc_18T_ms__and2_l g7726__5115 (.Y(n_497),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[22]));
   sky130_osu_sc_18T_ms__and2_l g7727__7482 (.Y(n_498),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[21]));
   sky130_osu_sc_18T_ms__and2_l g7728__4733 (.Y(n_499),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[20]));
   sky130_osu_sc_18T_ms__and2_l g7729__6161 (.Y(n_527),
	.A(n_482),
	.B(dwb_adr[21]));
   sky130_osu_sc_18T_ms__and2_l g7730__9315 (.Y(n_501),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[18]));
   sky130_osu_sc_18T_ms__and2_l g7731__9945 (.Y(n_512),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[7]));
   sky130_osu_sc_18T_ms__and2_l g7732__2883 (.Y(n_505),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[14]));
   sky130_osu_sc_18T_ms__and2_l g7733__2346 (.Y(n_506),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[13]));
   sky130_osu_sc_18T_ms__and2_l g7734__1666 (.Y(n_507),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[12]));
   sky130_osu_sc_18T_ms__and2_l g7735__7410 (.Y(n_508),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[11]));
   sky130_osu_sc_18T_ms__and2_l g7736__6417 (.Y(n_523),
	.A(n_482),
	.B(dwb_adr[25]));
   sky130_osu_sc_18T_ms__and2_l g7737__5477 (.Y(n_509),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[10]));
   sky130_osu_sc_18T_ms__and2_l g7738__2398 (.Y(n_513),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[6]));
   sky130_osu_sc_18T_ms__and2_l g7739__5107 (.Y(n_514),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[5]));
   sky130_osu_sc_18T_ms__and2_l g7740__6260 (.Y(n_515),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[4]));
   sky130_osu_sc_18T_ms__and2_l g7741__4319 (.Y(n_517),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[2]));
   sky130_osu_sc_18T_ms__and2_l g7742__8428 (.Y(n_518),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[1]));
   sky130_osu_sc_18T_ms__and2_l g7743__5526 (.Y(n_519),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[0]));
   sky130_osu_sc_18T_ms__and2_l g7744__6783 (.Y(n_500),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[19]));
   sky130_osu_sc_18T_ms__and2_l g7745__3680 (.Y(n_496),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[23]));
   sky130_osu_sc_18T_ms__and2_l g7746__1617 (.Y(n_490),
	.A(FE_OFN3_n_482),
	.B(dwb_dat_mosi[29]));
   sky130_osu_sc_18T_ms__and2_l g7747__2802 (.Y(n_487),
	.A(FE_OFN3_n_482),
	.B(dwb_we));
   sky130_osu_sc_18T_ms__and2_l g7748__1705 (.Y(n_538),
	.A(FE_OFN3_n_482),
	.B(dwb_adr[10]));
   sky130_osu_sc_18T_ms__or2_l g7749__5122 (.Y(n_6),
	.A(dwb_adr[28]),
	.B(n_4));
   sky130_osu_sc_18T_ms__inv_1 g7750 (.Y(n_5),
	.A(n_482));
   sky130_osu_sc_18T_ms__nor2_1 g7751__8246 (.Y(n_482),
	.A(dwb_adr[30]),
	.B(n_4));
   sky130_osu_sc_18T_ms__nand2_l g7752__7098 (.Y(n_4),
	.A(n_2),
	.B(n_3));
   sky130_osu_sc_18T_ms__nor2_l g7753__6131 (.Y(n_583),
	.A(system_reset),
	.B(n_1));
   sky130_osu_sc_18T_ms__nor2_l g7754__1881 (.Y(n_3),
	.A(dwb_adr[29]),
	.B(dwb_adr[31]));
   sky130_osu_sc_18T_ms__and2_l g7755__5115 (.Y(n_2),
	.A(dwb_cyc),
	.B(dwb_stb));
   sky130_osu_sc_18T_ms__inv_1 g7756 (.Y(n_1),
	.A(rst_n));
   sky130_osu_sc_18T_ms__inv_1 g7757 (.Y(n_0),
	.A(dwb_adr[16]));
endmodule

